---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: htpc-pvc
  namespace: htpc
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-pvc
  namespace: infra
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: utils-pvc
  namespace: utils
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
