---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: htpc-pv
  labels:
    type: arr-stack
spec:
  storageClassName: cluster-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/cluster/htpc
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-pv
  labels:
    type: infra
spec:
  storageClassName: cluster-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/cluster/infra
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: utils-pv
  labels:
    type: utils
spec:
  storageClassName: cluster-storage
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/cluster/utils
    type: DirectoryOrCreate
