{
 "title": "Scrape",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(scraparr_services_up,job)"
    }
   },
   {
    "name": "prowlarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"prowlarr\"},alias)"
    }
   },
   {
    "name": "sonarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"sonarr\"},alias)"
    }
   },
   {
    "name": "radarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"radarr\"},alias)"
    }
   },
   {
    "name": "bazarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"bazarr\"},alias)"
    }
   },
   {
    "name": "readarr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"readarr\"},alias)"
    }
   },
   {
    "name": "seerr",
    "query": {
     "query": "label_values(scraparr_services_up{scraparr_services=\"seerr\"},alias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Prowlarr ${prowlarr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "prowlarr",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scraparr_services_up{job=\"$job\", scraparr_services=\"prowlarr\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Build Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 5, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_build_time{job=\"$job\", alias=\"$prowlarr\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Scrape",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 11, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - prowlarr_last_scrape{job=\"$job\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - prowlarr_start_time{job=~\"$job\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Application Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_applications_total{job=\"$job\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Enabled Applications",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_application_enabled_total{job=\"$job\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Application Sync-Level",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_application_sync_level_total{job=\"scraparr\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Indexer Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_indexer_count{job=\"$job\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Enabled Indexers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_indexer_enabled{job=\"$job\", indexer=\"total\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Indexer Privacy",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_indexer_privacy{job=\"$job\", alias=\"$prowlarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Indexer VIP Expire in",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prowlarr_vip_expiration{job=\"$job\", alias=\"$prowlarr\"} - time()",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sonarr ${sonarr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "sonarr",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scraparr_services_up{job=\"$job\", scraparr_services=\"sonarr\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Build Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_build_time{job=\"$job\", alias=\"$sonarr\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Scrape",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - sonarr_last_scrape{job=\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - sonarr_start_time{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total/Missing Episodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Episodes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sonarr_missing_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total/Monitored/Ended/Continuing Series",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Series" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_series_total{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sonarr_monitored_series_total{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sonarr_ended_series{job=~\"$job\", path=\"total\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sonarr_continuing_series{job=~\"$job\", path=\"total\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used Disk Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_disk_size{job=\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "sonarr_disk_size_total{job=\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Disk Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_free_disk_size{job=\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quality Episode",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Episode" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_quality_episodes_total{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Genres Episode",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Episodes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonarr_genres_count_total{job=~\"$job\", alias=\"$sonarr\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Radarr ${radarr}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "radarr",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scraparr_services_up{job=\"$job\", scraparr_services=\"radarr\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Build Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_build_time{job=\"$job\", alias=\"$radarr\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Last Scrape",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - radarr_last_scrape{job=\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - radarr_start_time{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total/Downloaded/Monitored/Missing Movies",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Movies" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "radarr_movies_total{job=~\"$job\", alias=\"$radarr\"} - radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "radarr_monitored_movies_total{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "radarr_missing_movies_total{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used Disk Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_disk_size{job=\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "radarr_disk_size_total{job=\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Free Disk Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_free_disk_size{job=\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Quality's",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Movies" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_quality_movies_total{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Genres",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Movies" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "radarr_genres_count_total{job=~\"$job\", alias=\"$radarr\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}