---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-example-com
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  commonName: "*.my-homelab.party"
  dnsNames:
    - "my-homelab.party"
    - "*.my-homelab.party"
