---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dashboard
  - default-headers.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 28.0.0
    releaseName: traefik
    includeCRDs: true
    valuesFile: values.yaml
