---
globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.jellyfin-https.address=:8920"

deployment:
  enabled: true
  replicas: 1

ports:
  web:
    port: 80
    redirectTo:
      port: websecure
    protocol: TCP
  websecure:
    port: 443
    tls:
      enabled: true
    protocol: TCP
  jellyfin-https:
    port: 8920
    tls:
      enabled: true
    protocol: TCP

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.1.245

env:
  - name: TZ
    value: "CET"
