---
globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"

deployment:
  enabled: true
  replicas: 1

ports:
  web:
    port: 80
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    port: 443
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.1.245

env:
  - name: TZ
    value: "CET"
