apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

helmCharts:
  - name: netbird-operator
    repo: https://netbirdio.github.io/helm-charts
    version: 0.1.0 # Update to latest if needed
    releaseName: netbird-operator
    valuesFile: values.yaml
