apiVersion: v1
kind: Service
metadata:
  name: netbird-mgmt
  namespace: infra
spec:
  selector:
    app: netbird
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 80
      targetPort: 80
    - name: turn-udp
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: turn-tcp
      port: 3478
      protocol: TCP
      targetPort: 3478
  type: ClusterIP
