---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: htpc
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: htpc
spec:
  address: http://vault.infra.svc.cluster.local:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: htpc
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: htpc-vso
    serviceAccount: vault-auth
    audiences:
      - vault
