apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:PTuS1jtPf416e7O7pCDyIapEryptLNjAu/99jT1Li2ZiYz130xIrfX9akqVjul40uD9lxHlDOCExHoAHnN/CEA==,iv:i3qtD+cqzFtoa9Cgu+Dqv2goMG3FeTsCtuV6wq1AKQs=,tag:bQepiR5f832bxSZ7Sg9/eA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nfvx83fvk6fzm2hql7a0gq0k4w5q4d0y623fxcw23u3zr0vqzdesl73e43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbGpQYlVFd3N0c211ajVp
        bjJUdUZ0L1dHNGo0ZUNqTG5OODRJOUVob1JnCkUwRUtPTmJIcXEyWXZtSDB4aEcv
        UGppbzNPUk9ab2ZJL21BYXVya0RCK0EKLS0tIDVMemhuZHcxUnRvWk1ZSnZHaHRT
        Y2xDcUVOL0V1eWFQZXhtK2dHOWFScEUKKr5h+wkZ+59yRBHKoCQSof9lZdq2dQiI
        HuvYX6wlmFsaYCdB1e3W05jznnhO5ValXJzC8S3eEfDWTqtNJO7urA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T08:10:46Z"
  mac: ENC[AES256_GCM,data:DTThdK9MKLEvPUBuGZ4Wtk3fZz6zDRSDbNOGUBXUtBcdLP0QhdiWFsh6TlagLix0kbe2eTGbztBGFkEYic97SqdQxZMM17v/bNMfIntZQy8IaG2vo2WWOGgs/soDh+ZIx4FHIU/F+PuFiJ88aJku14bIbKWveoUkrg3QoYMCPuU=,iv:9GzBAKoCNRy+QpEKNaVZMMdLVFxFp5kZTIw+IpsiNY4=,tag:RDWYtCvtAoQv9qidDRInLw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
