---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: crowdsec-secrets
spec:
  encryptedData:
    BOUNCER_KEY_traefik: AgC9IOTF4Yqr3eJJJBuaJOvDmIvpIXAUVw5ICT7ilr8um008XRJ9ZmiMRp7j+3xM8g83xA9F1cScv468OR7sKSpYXEx39Q8PJE20IdsfAkjyrc89YHbT7zUfoQQ+On+ZdYVhdynUPqF50XPcImDS1R9RrZQ8tXQAHDz/YxvcY3XpIYMzqeHGpVZ8HN8YKnGAu1UIICIqhCedA72IQ/KMv7zup8V4amEjQvRUvzt+auPW7zqaEXDYbSjJCAyItLoPH/LPmx2450PCpY1tenQyqdkY/z1EUP2c/bjuHF4qspVbNF/HJW6SjJCtySFj6q/YS9NWZUUkhDOdGoCzAnGepvpKMehCXhnYnpj61ogMLg5voc2Es2k0pvUzY+Eg8eyw5wB+DKHAgKPr5Ex5UGQ+GTyuwAADAEqFYgRu54b2quV5oCzDyYib9AKrzBeoHKZChPb3hoTn/7YYZr4dv2VJtPCJI/kpOCKMpy2tX0qICKILP2glcADtfkk3SPlbsigcHi03N4xWptmXj3DtvlL6Gjbta9rDHf1WzrKX/njZ5TDbLhDmp6MO9xz3QXUE1BofI/Y6J/M3ur4RDbexyuD76kdgLCsw2kHieGa1JJSYUvjQDoe8lJj7IzqXNy86Ewiu2YSVymaeRZhlKV1ryf8FQRZiSKN1enFuwLkK4DXGcIk71xkBscWP55UU74dqYaRhek5cQc0Ii7R0RTmavt9Yn1hmLFQzbC6Lk0emN47x3+Rekc00jiAYR9OLoBsq7OPq0Am0D5UPrdOGO0dGuFjUWFcA
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: crowdsec-secrets
    type: Opaque
