---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: crowdsec-bouncer-key
spec:
  encryptedData:
    api-key: AgB7kiDafDfusL6JeI5B/MDhQqqLjhty5Vyae9fqx6MQm+ySELxCB+UNXTm4nQh8dPAXM2in4/kmvTTxigKxQ/BLsDVDQqEJdbCl9d+r5XhnwJsilr4vwSv1TD6fWmTBAxTPUfmQfpwWeb2iu0x+Y0fLxhFQcq7YRSGKAxEQo5ctdofl6ABVLCqzAXtmzwQdt9qym1c9NJD00uGejnta1H8IqwVtSsEVcUcs6EI5NrodfFHHXt0rwbCUkfBJ3X1r3N/A3rQaJGX8kGTvUWoazaqonjR4+gbcpR0JnH/TW9S7oDEWqyTTqWS9CWT5IBMf20ekPkWFFTKAGPGoonoajP2Eqa6Ea4jJUspSc7T1gGW3k+lRwz2hv1ZUaJ4kitM0qDIMG52095XU+Thf0YcRioiSBgp7vN0jewL9kxXQVwOT+/2B0tngGhrrU4xlQs3mo89PleCFVVIyotJ7dXeSgTOG7XntsCPBbgsKPgVbjCG8rf1/kqTvByDGmAaT+IWa/jfG0M+2WXDDCuNzSIPAmKUrATofeZMv18vdmOi0AywUiirSbcAQ2ZT2ZpXBTjEVKOrctioCwShuqGDmJT9eNTJptAMTzZ254qkevOSs9lWICieWYLyhFb0BGO63ZiYPMc6VFOpBa2b+WGp68oGHn44HaOZWWIjuStOPRwzsPHzlZrwjVt+yHON/u0uNSqDcCNE72TJPXyfsiwYySwgVZhFSILUfu403bSNCkd/L0zsgTT8wDXYC3QXagGQs5qOU/3aUqud3SxDba0QpHYste/jk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: crowdsec-bouncer-key
    type: Opaque
