apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-secrets
type: Opaque
stringData:
  BOUNCER_KEY_traefik: ENC[AES256_GCM,data:AbMS2IFol2aVbIONkVoqQwFKd6NTV6TGf1bguRg/C8HC3zImWJhqtFabRice+xhMMEKBL1SuLx/EdFUI3cr9ng==,iv:Du2+okDHVGe9hsymP06kxPefQ5pVXO4huq4N74myad8=,tag:/ol/3n4J5sm8EI+PIG4UGg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nfvx83fvk6fzm2hql7a0gq0k4w5q4d0y623fxcw23u3zr0vqzdesl73e43
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRG1nOVcxRXZ4RktqSFNq
        UFlJK2pwRVdBR0lrSDNYaG5VK0RhUmlVVmo0CkxPcUEyc014KzhxY3JWUTNoVUV2
        WDJoOEZVNnV4dHErb3dOYzdMUXZDa1kKLS0tIHNiRzNLQm9HaUNVVmV2bzcwZGZq
        UzBtSVB1MllZdjBnTVBlQ3ZaOGVVbHMKq/SRLfr702NC1JH5rjv30g3TATvpnaLy
        aivyv6YaWJjbVK/1fL0nL2cKgG9gGLT9EEOO9m2+1PMaw8dVx3ZKEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T08:10:37Z"
  mac: ENC[AES256_GCM,data:TeLr574EcsKjTjBVZkC9nUmYGBjn4iIKfTsIUsXc/eAnuSnMkpP2BAQ8RiHEKOT1tjoWtyORvTi2AV0+N35OCGGAU6mKQDIpn76sTV+alZwNBSpd8Sz4nz/5KHcRYu33zGSjlqNcDWhv8l8mt/fwKkE7mhEZg9vdwwWfymqAQwY=,iv:YQLx+DtewX6gr9lje3qN2T4Efl3OHyarv9Jr1QMij5E=,tag:Zre84Oc1fHykr/VeoHjRwg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.4
