---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: crowdsec-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - crowdsec-secrets.yaml
  - crowdsec-bouncer-key.yaml
