---
global:
  leaderElection:
    namespace: "infra"
namespace: "infra"
clusterResourceNamespace: infra
replicaCount: 1
extraArgs:
  - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 1.1.1.1
    - 9.9.9.9

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    prometheusInstance: infra
    labels:
      release: kube-prometheus-stack
    targetPort: 9402

crds:
  enabled: false

extraEnv:
  - name: TZ
    value: CET
