---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cloudflare-token-secret
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - secret-cloudflare-token.yaml
