---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:K9auWZceaB+OKYsno7v/SGQMFfoxXzjL3HEhddweS7FaEhhSALZkWHspvE4QpbYK8Cac6xFF3iizeG9yjVXzVXlvFXp+wfNmL9AvuZO3v328SFP/s43gbaECJN24bnnmwLulPFnTaH5IFOJD5ZObe9YCBg8urpVkrC/yn8FdZvsypST6LKwgR6q/n9yu+Q==,iv:nrO6Zlkexdjf1mf00cG215EPWhijFDOpMK0Y2MrZEVs=,tag:cHTmxAUsC/X3WxleoCCaUw==,type:comment]
    cloudflare-token: ENC[AES256_GCM,data:8oJO6RQv4AOv55KLqpwXlyia/VY74Be+s7823mEkL1FGd/OHZjXadA==,iv:g90eBLm2Jm6o5yGQPhJPkPLicXQvrp66vDkMIstcSXM=,tag:CcVFQQpMjitnfJcaKRqHFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfvx83fvk6fzm2hql7a0gq0k4w5q4d0y623fxcw23u3zr0vqzdesl73e43
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaXJLeE9UcWFpRXpPT0V5
            dnQwTHRaTWJOSkVlNVcybG84RHZiK0ZaeFdvCjQydWVhZEcwM2JZQ25lV0pqS2Iw
            UnNLdnFJZ2Q0aVp4WTA3UjJsQmJpZ2sKLS0tIE1nWlBibHdoVTBYanhCZjFVRC9t
            QnE3MEgyK0luaW1WVnpucnVPalhSQ00KAyz3B9aAIMVFAsPgI5wVNVb8Dv7rBvet
            lImbSi9CWMjyztuZzt10AU/8CrK6uj12asAFb7tG8860B/9CTh39gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T19:28:27Z"
    mac: ENC[AES256_GCM,data:YUq6yKXp+ill5r2vWS1eQCxIPG9rhJWc1nnVtmC2k6a6JrYhjW/kuJo26CLEFa/GnhcEKvFO1ii5smVfa9WJnX1u9FBS1pPxEZRDqk52i2/5Gjhd3aZcFFPc9D/ZTBDp/cJtMmBa48Zz/4jeSR9ZBKhjGguMpyzIKDvxlZbCwbM=,iv:zfFo6OD+QZ9VqfVlsL24jIr7Af+ommR2u7R0vx3f0xk=,tag:Bn/jfTiFuGTUUI4k/Bw7FQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
