---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-credentials
  namespace: utils
spec:
  encryptedData:
    NEXTCLOUD_ADMIN_USER: AgREPLACE_WITH_KUBESEAL_OUTPUT
    NEXTCLOUD_ADMIN_PASSWORD: AgREPLACE_WITH_KUBESEAL_OUTPUT
    DB_USERNAME: AgREPLACE_WITH_KUBESEAL_OUTPUT
    DB_PASSWORD: AgREPLACE_WITH_KUBESEAL_OUTPUT
    username: AgREPLACE_WITH_KUBESEAL_OUTPUT
    password: AgREPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: nextcloud-credentials
      namespace: utils
    type: Opaque
