---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: nextcloud-credentials
  namespace: utils
spec:
  type: kv-v2
  mount: kv
  path: utils/nextcloud
  vaultAuthRef: vault-auth
  refreshAfter: 30s
  destination:
    create: true
    name: nextcloud-credentials
    overwrite: true
