---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radarr
  template:
    metadata:
      labels:
        run: radarr
    spec:
      initContainers:
        - name: check-config-dir
          image: busybox
          command: ['sh', '-c', 'mkdir -p /config && touch /config/config.xml && echo "<Config><UrlBase>/radarr</UrlBase></Config>" > /config/config.xml']
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: radarr
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /movies && chown -R 911:911 /movies"]
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /movies
              subPath: media/movies
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 7878
              name: webui
          startupProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: radarr
            - name: arr-stack-storage
              mountPath: /movies
              subPath: media/movies
            - name: arr-stack-storage
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: arr-stack-pvc
