---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radarr
  template:
    metadata:
      labels:
        run: radarr
    spec:
      initContainers:
        - name: check-config-dir
          image: busybox
          command: ['sh', '-c', 'mkdir -p /config && touch /config/config.xml && echo "<Config><UrlBase>/radarr</UrlBase></Config>" > /config/config.xml']
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: radarr
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
              name: webui
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl "http://localhost:7878/radarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl "http://localhost:7878/radarr/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: radarr
            - name: arr-stack-storage
              mountPath: /movies
              subPath: media/movies
            - name: arr-stack-storage
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: arr-stack-pvc
