---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ingress-route.yaml
  - application.yaml
  # - https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v2.14.4/manifests/install.yaml
  - argo-non-crds.yaml
patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
    path: configmap.yaml
  - target:
      kind: Deployment
      name: argocd-repo-server
    path: deployment.yaml
