---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: placeholder-server
    email: chaitanya2692@gmail.com
    privateKeySecretRef:
      name: placeholder-name
    solvers:
      - dns01:
          cloudflare:
            email: chaitanya2692@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "my-homelab.party"
