---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: infra
spec:
  encryptedData:
    cloudflare-token: AgREPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: infra
    type: Opaque
