---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-token-secret
spec:
  encryptedData:
    cloudflare-token: AgDDhKQsWkxbsJYFKlTSD6hI3HFzoW8pRTGIlBYVGYzEgp/8UPwWzcAP9y2gQPjASxXm97aN4HNN8jM60zOAtPqYMU1CJPoCGjTx68TTOR46SO1DSAqgMg0bHnILiU+m7zUS7Wkps1jLaoCI+fr1OGSe28aa2QuaIBvibp3LGaZwXbc8m3Y9xPwRCH8N+MfXli1v9uLt1DGf1DdzNmKb3RZEkKF6qKYXtByuZLS8DkeQD9+QiEXAo2s6KylaVweR369s0dxwRLiCDxLE6FPt9wlvSPoo6RSWGVhjqJGYLY7XfcKTNWXfzKAU31g1k3uZejbWAv/gggsQ9CkCsw6oLP2e59rplGFu4TMECNoJ/5+Wax/KZesO+4jcupNm0e7kfOb2LRd6EjVyTpsdmB0N2sv9AU6LINWOgnf7jxKFzNkQmoJxBzpSKnTUgxHwwMIESFLDZm9eQJRbvCi1MTuaZrujV2njuximQHZTGnyuD6CPpXMgYduDKBlW/WTfGbfLXhD9Aw9SpVmg6ULUv4gBZYnxBYFFcccsvMrOEeyslzB2FJRkvoEwlYsdABEFGTkCQD3tPnLmcX8xCS4/JSgcqt/TQZ+o28UB4p/Q8O2tFYi9La1jFicLL2svayvYxs8FOhaeIR5Aej1f98BGWlr1jMszh9oXYf1IvHI9k5x8VOrJlfdCvOkG2ifZn4iIUQ4RXbqZm0qIjiSc79V7O8YArkpvG6YSOoPHDAgExx0H86eWsrsyY8XKMAmxJHRdK1oTBP3Vi3PD3A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-token-secret
    type: Opaque
