---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-token-secret
spec:
  encryptedData:
    cloudflare-token: AgAS/Ei4YmxRw1CBjnB0KetnKpyWdzx7hLf7bQliNLy5JSAdVKvShI7x4w7JFDJ9G8ISEqH8OFDggdfLS1MHP8D+ZvDSs4D9Wduw5ylSuf9A+3xQ/PbOCDtgbuGqTKI4SJoEHCClUhdU+30pPRNwXcZ7aHd/t+lDT2PDGhL/feAsfGV9K2K/Sx0mzAtmF0Pzn7fLYDEZageUBL4c/4cVITJOyvINqRkb3g2Xt6muHcE1T0mL3gu5GzZzjVGdEydvFpuRBwKPUOMpOO7ReDOZduf3prKZY1kv9A8lsoFRRpHaDLt7v8MblOG9HyukBsed9OFBR8LfwXVre2cvcliUsP0ew399BV6u2Ef/bhZAgO9EK2rJr+vtjGgXG8G4RJKCt3Ad6ziwTCbeVLI7Gdlih3aWaBTXnmmHXcvYiy4pd7lMTWt432/8BkbXjE0/jC5K5+42Fp+jJHCUIWhBHdXg5QihMIgsEN8qyCrxf2AuSOE3xnrnh4e7XOlIjQu+H6F4keQ73/0bFo5vfFu0mWKfTdWknTNGlCqeRBm1oujuP3Fjqgxso2bUB6hULohW21brjuItz+P9ZXVFD1aOf+2APJK2gEqR2E+LwtFUmMrD5mjJ+tXafz9ubFaOHCsp3JrOhtpwcs2s1Q//XiBgczZDaH30rH63KOft7qpQ773hCkW6EIY7g3rh6Fs98QAc3aEfevPWl5yERlz3HROVCY7nj0i06+VaR5eZQodOl66+aC4e8m8aAXeZCty5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-token-secret
    type: Opaque
