---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cloudflare-token-secret
spec:
  encryptedData:
    cloudflare-token: AgBKesBX6KMPVFoB4P63Q3rH/RUW6dJQR3SlIt74zidaQQoaDSjQiUJPyiUJpanAw4DUontvGzzEn6Sz1Dl3iz2Fnnwfxitgtaq2WYkMrp9H9XdQmTz3RQ/ITq4C1xqEG/TLX2l8k2KjNQFgZy1zfR13aAJAxgxm9pXFgaEPwGMqvxkVse3buPY8d2yUKMyfgIeWXlTgGZWd2Ng3urB7bT9jbc0OLd4VMe/M0FLH2RKvhqY4VYH+1FSDoyn51iuaE8avs1vaV4c84KV1S+IREd0VKlSqjs3ssGhdXGvqfSN/HHW2BtDNGDIoDNteCaM2VpLjnyiGSjaUoYchqwcGBwNDnuU8HpbRu+zq7Q8A7UOuI0tkGO5ku7KNEK+uhKqX6uD5GDkZAQpkXvW1v2QFHgZdkZAh+E703IV4dZQLHLApJ4g0c5REoCbmUP31pPQu/p3x6nFOR1Whs0EHqJBHBzJvAMP1e4Og42Ewgg/MUDqJWWiTqnblIbrUSFJA+hou59LSBEf/q8k7BVg4UiwkmnDNp12nYaDtqev766bXpZN4AGDj8KciXvvm1udcDg67DIO2VOLmjbRKATsCFUjUcT9mvqDClQSLWhHyyNkiWoZUYdbS9lVd6AlbrHod0wVG6VE34uTakQDTJ2GkKwOM2rGIq6hcjfYpnhj2oJGP4SM/tm9mhFnOTJamaTdi7Okp94h/g1ohsgM6WNy7DEy8RN4VGBE/cWwjN8V1UbXEZ6JcbRbcdsRoJW35LYWr734UKdnR0/wTFA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cloudflare-token-secret
    type: Opaque
