---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-token-secret
  namespace: infra
spec:
  type: kv-v2
  mount: kv
  path: infra/cert-manager
  vaultAuthRef: vault-auth
  refreshAfter: 30s
  destination:
    create: true
    name: cloudflare-token-secret
    overwrite: true
