config:
  default: true

  line-length:
    code_blocks: false
    tables: false
    line_length: 800
  no-inline-html: false

ignores:
  - "**/.venv/**"
  - "**/venv/**"
  - "**/.github/**"
  - "**/site/**"
  - "**/node_modules/**"
  - plan_authelia.md
  - plan_vault.md
