---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 800
    level: warning

ignore:
  - install.yaml
  - crds.yaml
  - non-crds.yaml
