---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-apps
spec:
  generators:
    - list:
        elements:
          - path: infra-security
            namespace: infra
            syncWave: "-1"
          - path: infra
            namespace: infra
            syncWave: "0"
          - path: utils
            namespace: utils
            syncWave: "1"
          - path: htpc
            namespace: htpc
            syncWave: "1"
  template:
    metadata:
      name: "{{path}}-apps"
      annotations:
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/chaitanya2692/my-homelab.git
        targetRevision: main
        path: overlays/{{path}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: postgresql.cnpg.io
          kind: Cluster
          jsonPointers:
            - /spec/managed/roles/0/connectionLimit
            - /spec/managed/roles/0/ensure
            - /spec/managed/roles/0/inherit
            - /status
        - group: apps
          kind: StatefulSet
          name: recipes-postgresql
          namespace: utils
          jsonPointers:
            - /spec/volumeClaimTemplates/0/apiVersion
            - /spec/volumeClaimTemplates/0/kind
            - /status
