---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jackett
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jackett
  template:
    metadata:
      labels:
        run: jackett
    spec:
      initContainers:
        - name: config
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args:
            - "echo start;
            [[ ! -f /config/Jackett/ServerConfig.json ]] && mkdir -p /config/Jackett/ &&  echo '{ \"BasePathOverride\": \"/jackett\"}' > /config/Jackett/ServerConfig.json;
            echo end;"
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: jackett
      containers:
        - name: jackett
          image: linuxserver/jackett:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9117
              name: webui
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: jackett
            - name: arr-stack-storage
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: arr-stack-pvc
