---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: linuxserver/jackett
    newTag: latest
  - name: linuxserver/sonarr
    newTag: latest
  - name: linuxserver/radarr
    newTag: latest
  - name: linuxserver/bazarr
    newTag: latest
  - name: linuxserver/transmission
    newTag: latest
  - name: emby/embyserver
    newTag: latest
