---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`longhorn.my-homelab.party`)
      priority: 10
      services:
        - name: longhorn-frontend
          port: 80
      middlewares:
        - name: homelab-auth
          namespace: infra
        - name: default-headers
          namespace: infra
