apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - namespace.yaml
  - storageclass.yaml
  - ingress-route.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.8.1
    releaseName: longhorn
    namespace: longhorn-system
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: longhorn-service-account
    target:
      kind: ServiceAccount
      name: longhorn-service-account
