---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-utils
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  dataLocality: "disabled"
