---
defaultSettings:
  defaultDataPath: "/opt/cluster/utils/"
persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain
preUpgradeChecker:
  jobEnabled: false # Keep this as you had it for GitOps
