---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-backups
  labels:
    run: nextcloud-backups
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nextcloud-backups
  template:
    metadata:
      labels:
        run: nextcloud-backups
    spec:
      containers:
        - name: nextcloud-backups
          image: postgres:16
          command:
            - /bin/sh
            - -c
          args:
            - |
              sh -c 'sleep $BACKUP_INIT_SLEEP &&
              while true; do
                pg_dump -h postgres -p 5432 -d $NEXTCLOUD_DB_NAME -U $NEXTCLOUD_DB_USER | gzip > $POSTGRES_BACKUPS_PATH/$POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
                tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH &&
                find $POSTGRES_BACKUPS_PATH -type f -mtime +$POSTGRES_BACKUP_PRUNE_DAYS | xargs rm -f &&
                find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS | xargs rm -f;
                sleep $BACKUP_INTERVAL; done'
          envFrom:
            - configMapRef:
                name: nextcloud-env
            - configMapRef:
                name: global-env
            - secretRef:
                name: nextcloud-credentials
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-credentials
                  key: NEXTCLOUD_DB_PASSWORD
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
              subPath: nextcloud
            - name: nextcloud-data
              mountPath: /srv/nextcloud-postgres/backups
              subPath: postgres-backups
            - name: nextcloud-data
              mountPath: /srv/nextcloud-application-data/backups
              subPath: nextcloud-backups
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
