# File: base/utils/nextcloud/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret
  - configmap.yaml
  - nextcloud-deployment.yaml
  - nextcloud-service.yaml
  - nextcloud-cronjob.yaml
  - postgres-cluster.yaml
  # - postgres-backup.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - middleware.yaml

generatorOptions:
  disableNameSuffixHash: true
