---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    run: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nextcloud
  template:
    metadata:
      labels:
        run: nextcloud
    spec:
      securityContext:
        fsGroup: 33
      initContainers:
        - name: set-perms-and-copy-config
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              mkdir -p /var/www/html/config
              chown -R 33:33 /var/www/html
              cp /config-src/custom.config.php /var/www/html/config/custom.config.php
              chown 33:33 /var/www/html/config/custom.config.php
              echo "Permissions set and config copied successfully."
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: nextcloud-data
              subPath: nextcloud/app
              mountPath: /var/www/html
            - name: nextcloud-config-vol
              mountPath: /config-src
              readOnly: true
        - name: wait-for-db
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - |
              until nc -z redis 6379 && nc -z nextcloud-db-rw 5432; do
                echo "Waiting for Redis and PostgreSQL (CNPG)..."
                sleep 5
              done
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          envFrom:
            - secretRef:
                name: nextcloud-credentials
          env:
            - name: POSTGRES_HOST
              value: nextcloud-db-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_HOST
              value: "redis"
            - name: PHP_MEMORY_LIMIT
              value: "512M"
            - name: PHP_UPLOAD_LIMIT
              value: "512M"
            - name: POSTGRES_DB
              value: nextcloud-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-credentials
                  key: password
          volumeMounts:
            - name: nextcloud-data
              subPath: nextcloud/app
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: nextcloud-config-vol
          configMap:
            name: nextcloud-config
