---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cron
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 33
            runAsGroup: 33
          containers:
            - name: nextcloud-cron
              image: nextcloud:latest
              command:
                - /bin/sh
                - -c
                - php -f /var/www/html/cron.php
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              volumeMounts:
                - name: nextcloud-data
                  subPath: nextcloud/app
                  mountPath: /var/www/html
          restartPolicy: OnFailure
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: utils-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-maintenance
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: "0 2 * * *" # Run at 2 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 33
            runAsGroup: 33
          containers:
            - name: nextcloud-maintenance
              image: nextcloud:latest
              command:
                - /bin/sh
                - -c
                - |
                  php occ maintenance:mode --on
                  php occ maintenance:repair --include-expensive
                  php occ db:add-missing-indices
                  php occ db:convert-filecache-bigint
                  php occ files:scan-app-data
                  php occ files:cleanup
                  php occ files:scan --all
                  php occ maintenance:mimetype:update-js
                  php occ maintenance:mode --off
                  php occ occ config:system:set maintenance_window_start --type=integer --value=1
                  php occ config:system:set default_phone_region --value="SE"
                  php occ config:system:set skeletondirectory --value=''
                  php occ update:check
                  php occ status
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "250m"
                limits:
                  memory: "1Gi"
                  cpu: "500m"
              volumeMounts:
                - name: nextcloud-data
                  subPath: nextcloud/app
                  mountPath: /var/www/html
          restartPolicy: OnFailure
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: utils-pvc
