apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-db
  namespace: utils
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"

  # Remove managed roles - let CNPG create the standard '-app' secret for the owner
  # managed:
  #   roles:
  #     - name: nextcloud
  #       login: true
  #       passwordSecret:
  #         name: nextcloud-credentials
  #         key: NEXTCLOUD_DB_PASSWORD

  bootstrap:
    initdb:
      # The owner specified here will have credentials generated in the '<cluster-name>-app' secret
      database: nextclouddb
      owner: nextcloud

  storage:
    storageClass: local-path-utils
    size: 10Gi

  backup:
    retentionPolicy: "30d"
    volumeSnapshot:
      className: local-path-utils
      snapshotOwnerReference: "cluster"
