---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    run: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli ping | grep PONG
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: nextcloud-data
              subPath: redis
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
