---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    run: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      # Consider adding fsGroup if redis image needs specific group permissions
      # securityContext:
      #   fsGroup: <redis_group_id_if_needed>
      containers:
        - name: redis
          image: redis:7.4
          args: ["--requirepass", "$(REDIS_HOST_PASSWORD)"]
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: nextcloud-env
            - secretRef:
                name: nextcloud-credentials
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - redis-cli -a $REDIS_HOST_PASSWORD ping | grep PONG
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: nextcloud-data
              mountPath: /data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
