---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infra
  namespace: infra
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.my-homelab.party`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
