---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd
  - cert-manager
  - metallb
  - traefik
  - ingress-route.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
