---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - cert-manager
  - metallb
  - traefik
  - local-path-provisioner
  - ingress-route.yaml
  # Add PVC back when in use
  # - persistent-volume-claim.yaml
