---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - cert-manager
  - metallb
  - traefik
  - local-path-provisioner
  - monitoring
  - authentik
  - vault
  - netbird
  - ingress-route.yaml
  - persistent-volume-claim.yaml

commonLabels:
  app.kubernetes.io/part-of: infrastructure
