---
# PVC for Grafana Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # For dashboards, plugins, internal DB

---
# PVC for Jaeger Storage (Only if using persistent storage like Badger)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-data-pvc # Adjust if needed based on Jaeger chart values
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PVC for Promtail Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-positions-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# PVC for Authentik Media
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# PVC for Authentik Redis
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# PVC for Vault Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# PVC for NetBird Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbird-data-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
