---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      type: infra
