---
# PVC for Prometheus Data (kube-prometheus-stack)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-kube-prometheus-stack-db-pvc # Match expected name pattern or configure in values
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests: # Adjust size based on retention and scrape frequency
      storage: 20Gi

---
# PVC for Alertmanager Data (kube-prometheus-stack)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-kube-prometheus-stack-db-pvc # Match expected name pattern or configure in values
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Usually smaller than Prometheus

---
# PVC for Grafana Data (kube-prometheus-stack)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-kube-prometheus-stack-pvc # Match expected name pattern or configure in values
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # For dashboards, plugins, internal DB

---
# PVC for Loki Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce # Loki components might run as StatefulSet/Deployment needing RWO
  resources:
    requests: # Adjust based on log volume and retention
      storage: 4Gi
---
# PVC for Jaeger Storage (Only if using persistent storage like Badger)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-data-pvc # Adjust if needed based on Jaeger chart values
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PVC for Promtail Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-positions-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# PVC for Traefik Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
