---
# PVC for Traefik Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data-pvc
  namespace: infra
spec:
  storageClassName: local-path-infra
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
