apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - ingress-route.yaml
  - dashboards

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 87.5.1
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values-kube-prometheus-stack.yaml
    includeCRDs: true

  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 7.0.0
    releaseName: loki
    namespace: monitoring
    includeCRDs: true
    valuesFile: values-loki.yaml

  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.10.0
    releaseName: alloy
    namespace: monitoring
    includeCRDs: true
    valuesFile: values-alloy.yaml

  - name: jaeger
    repo: https://jaegertracing.github.io/helm-charts
    version: 4.11.1
    releaseName: jaeger
    namespace: monitoring
    includeCRDs: true
    valuesFile: values-jaeger.yaml
