---
namespaceOverride: "monitoring"
fullnameOverride: prometheus

grafana:
  enabled: true
  fullnameOverride: grafana
  defaultDashboardsTimezone: cet
  grafana.ini:
    analytics:
      check_for_updates: false
      reporting_enabled: false
      check_for_plugin_updates: false
  persistence:
    enabled: true
    existingClaim: grafana-data-pvc
  initChownData:
    enabled: false
  sidecar:
    dashboards:
      enabled: true
      skipTlsVerify: true
    datasources:
      enabled: true
      skipTlsVerify: true

prometheus:
  enabled: true
  serviceAccount:
    create: true
    name: kube-prometheus-stack-prometheus
  prometheusSpec:
    replicas: 1
    replicaExternalLabelName: "replica"
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    retention: 7d
    enableAdminAPI: true
    walCompression: true
    additionalScrapeConfigs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            action: keep
            regex: "true"
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
            regex: "(.+)"
            replacement: $1
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
            regex: ^$
            replacement: /metrics
            action: replace
          - source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            target_label: __address__
            regex: '([^:]+)(?::\d+)?;(\d+)'
            replacement: $1:$2
            action: replace
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: kubernetes_namespace
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: kubernetes_pod_name
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container_name
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
            target_label: app_kubernetes_io_name
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
            target_label: app_kubernetes_io_instance
            action: replace
          - source_labels:
              - __meta_kubernetes_pod_label_run
            target_label: run
            action: replace
    resources:
      requests:
        cpu: "150m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "1536Mi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path-monitoring
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

nodeExporter:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node

prometheus-node-exporter:
  enabled: true
  fullnameOverride: node-exporter
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  enabled: true
  fullnameOverride: kube-state-metrics
  selfMonitor:
    enabled: true
  prometheus:
    monitor:
      enabled: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: kubernetes_node
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

alertmanager:
  enabled: false
kubeApiServer:
  enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

kubeControllerManager:
  enabled: true
  endpoints:
    - 192.168.1.75

coreDns:
  enabled: true

kubeDns:
  enabled: false

kubeEtcd:
  enabled: true
  endpoints:
    - 192.168.1.75
  service:
    enabled: true
    port: 2381
    targetPort: 2381

kubeScheduler:
  enabled: true
  endpoints: # ips of servers
    - 192.168.1.75

kubeProxy:
  enabled: true
  endpoints: # ips of servers
    - 192.168.1.75
