---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-backups
  labels:
    run: nextcloud-backups
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nextcloud-backups
  template:
    metadata:
      labels:
        run: nextcloud-backups
    spec:
      containers:
        - name: backups
          image: postgres:13
          command:
            - /bin/sh
            - -c
          args:
            - |
              sleep $BACKUP_INIT_SLEEP
              while true; do
                su postgres -c "pg_dump -h postgres -p 5432 -d $POSTGRES_DB -U $POSTGRES_USER" | gzip > $POSTGRES_BACKUPS_PATH/$POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz
                su www-data -c "tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH"
                find $POSTGRES_BACKUPS_PATH -type f -mtime +$POSTGRES_BACKUP_PRUNE_DAYS -delete
                find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS -delete
                sleep $BACKUP_INTERVAL
              done
          envFrom:
            - configMapRef:
                name: nextcloud-env
          volumeMounts:
            - name: nextcloud-storage
              mountPath: /var/www/html
              subPath: html
            - name: nextcloud-storage
              mountPath: /backups
              subPath: backups
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-pvc
