apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nextcloud-deployment.yaml
  - nextcloud-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - backups-deployment.yaml
  - middleware.yaml

configMapGenerator:
  - name: nextcloud-env
    literals:
      # Nextcloud Admin Credentials
      - NEXTCLOUD_ADMIN_USER=nextcloudadmin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloudpassword

      # Database Configuration
      - NEXTCLOUD_DB_NAME=nextclouddb
      - NEXTCLOUD_DB_USER=nextclouduser
      - NEXTCLOUD_DB_PASSWORD=nextcloud_password

      # Redis Configuration
      - REDIS_HOST_PASSWORD=redis_password

      # Backup Configuration
      - BACKUP_INIT_SLEEP=30m
      - BACKUP_INTERVAL=24h
      - POSTGRES_BACKUP_PRUNE_DAYS=7
      - DATA_BACKUP_PRUNE_DAYS=7
      - POSTGRES_BACKUPS_PATH=/srv/nextcloud-postgres/backups
      - DATA_BACKUPS_PATH=/srv/nextcloud-application-data/backups
      - DATA_PATH=/var/www/html
      - POSTGRES_BACKUP_NAME=nextcloud-postgres-backup
      - DATA_BACKUP_NAME=nextcloud-application-data-backup

generatorOptions:
  disableNameSuffixHash: true
