---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nextcloud-deployment.yaml
  - nextcloud-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - backups-deployment.yaml

configMapGenerator:
  - name: nextcloud-env
    literals:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=password
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.my-homelab.party
      - OVERWRITEPROTOCOL=https
      - BACKUP_INIT_SLEEP=3600
      - BACKUP_INTERVAL=86400
      - NEXTCLOUD_DB_NAME=nextcloud
      - NEXTCLOUD_DB_USER=admin
      - POSTGRES_BACKUPS_PATH=/backups/postgres
      - DATA_BACKUPS_PATH=/backups/data
      - POSTGRES_BACKUP_NAME=nextcloud-db-backup
      - DATA_BACKUP_NAME=nextcloud-data-backup
      - DATA_PATH=/var/www/html
      - POSTGRES_BACKUP_PRUNE_DAYS=7
      - DATA_BACKUP_PRUNE_DAYS=7

generatorOptions:
  disableNameSuffixHash: true
