---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-securityheaders
  namespace: htpc
spec:
  headers:
    stsSeconds: 15552000
    stsIncludeSubdomains: true
    stsPreload: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    browserXssFilter: true
    customResponseHeaders:
      Referrer-Policy: "no-referrer"
      Permissions-Policy: "interest-cohort=()"
    sslRedirect: true
    forceSTSHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirectregex1
  namespace: htpc
spec:
  redirectRegex:
    permanent: true
    regex: "https?://([^/]*)/.well-known/(card|cal)dav"
    replacement: "https://${1}/remote.php/dav/"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirectregex2
  namespace: htpc
spec:
  redirectRegex:
    permanent: true
    regex: "https?://([^/]*)(/.well-known[^#]*)"
    replacement: "https://${1}/index.php${2}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-compress
  namespace: htpc
spec:
  compress: {}
