---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    run: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nextcloud
  template:
    metadata:
      labels:
        run: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: nextcloud-env
          env:
            - name: POSTGRES_HOST
              value: postgres
            - name: REDIS_HOST
              value: redis
          volumeMounts:
            - name: nextcloud-data
              subPath: nextcloud
              mountPath: /var/www/html
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
