---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vault-secrets-operator
    repo: https://helm.releases.hashicorp.com
    version: 0.10.0
    releaseName: vault-secrets-operator
    namespace: infra
    includeCRDs: true
    valuesFile: values.yaml
