---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: prowlarr
  name: prowlarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: prowlarr
  template:
    metadata:
      labels:
        run: prowlarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9696"
        prometheus.io/path: "/prowlarr/metrics"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: TZ
              value: "CET"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9696
              name: webui
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: prowlarr
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: htpc-pvc
