---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: bazarr
  name: bazarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: bazarr
  template:
    metadata:
      labels:
        run: bazarr
    spec:
      initContainers:
        - name: wait-for-sonarr-and-radarr
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'echo "Waiting for Radarr to be ready..."; sleep 60']
        - name: config
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - |
              mkdir -p /htpc/bazarr/config
              export RADARR_API_KEY=$(cat /htpc/radarr/config.xml | sed -ne "/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}")
              export SONARR_API_KEY=$(cat /htpc/sonarr/config.xml | sed -ne "/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}")
              cat << EOF > /htpc/bazarr/config/config.ini
              [sonarr]
              apikey = ${SONARR_API_KEY}
              full_update = Daily
              ip = $(SONARR)
              only_monitored = False
              base_url = /$(SONARR)
              ssl = False
              port = 8989

              [radarr]
              apikey = ${RADARR_API_KEY}
              full_update = Daily
              ip = $(RADARR)
              only_monitored = False
              base_url = /$(RADARR)
              ssl = False
              port = 7878

              [general]
              movie_default_hi = False
              movie_default_language = []
              ip = 0.0.0.0
              use_scenename = True
              use_postprocessing = False
              enabled_providers = subscene,tvsubtitles
              auto_update = True
              port = 6767
              use_radarr = True
              base_url = /bazarr/
              page_size = 25
              minimum_score_movie = 70
              branch = master
              single_language = False
              use_sonarr = True
              serie_default_hi = False
              path_mappings_movie = [['/movies', '/movies'], ['', ''], ['', ''], ['', ''], ['', '']]
              serie_default_enabled = False
              movie_default_enabled = False
              serie_default_language = []
              path_mappings = [['/tv', '/tv'], ['', ''], ['', ''], ['', ''], ['', '']]
              postprocessing_cmd =
              minimum_score = 90
              debug = False
              use_embedded_subs = True
              adaptive_searching = False
              EOF
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /htpc
      containers:
        - name: bazarr
          image: linuxserver/bazarr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6767
              name: webui
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: bazarr
            - name: arr-stack-storage
              mountPath: /movies
              subPath: media/movies
            - name: arr-stack-storage
              mountPath: /tv
              subPath: media/tv
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: arr-stack-pvc
