---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/cert.yaml
  - path: patches/issuer.yaml
  - path: patches/ingress-route.yaml
    target:
      kind: IngressRoute
      name: ingressroute
