---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../argocd

images:
  - name: linuxserver/jackett
    newTag: latest
  - name: linuxserver/sonarr
    newTag: latest
  - name: linuxserver/radarr
    newTag: latest
  - name: linuxserver/bazarr
    newTag: latest
  - name: linuxserver/transmission
    newTag: latest
  - name: linuxserver/jellyfin
    newTag: latest

patches:
  - path: patches/cert.yaml
  - path: patches/issuer.yaml
