---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: linuxserver/jackett
    newTag: latest
  - name: linuxserver/sonarr
    newTag: latest
  - name: linuxserver/radarr
    newTag: latest
  - name: linuxserver/bazarr
    newTag: latest
  - name: linuxserver/transmission
    newTag: latest
  - name: jellyfin/jellyfin:10.9.9
    newTag: latest

patches:
  - path: patches/cert.yaml
  - path: patches/issuer.yaml
