apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: scraparr
  namespace: htpc
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: scraparr
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
