---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: exportarr-secrets
  namespace: htpc
spec:
  encryptedData:
    SONARR_API_KEY: AgREPLACE_WITH_KUBESEAL_OUTPUT
    RADARR_API_KEY: AgREPLACE_WITH_KUBESEAL_OUTPUT
    PROWLARR_API_KEY: AgREPLACE_WITH_KUBESEAL_OUTPUT
    JELLYFIN_API_KEY: AgREPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: exportarr-secrets
      namespace: htpc
    type: Opaque
