---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: exportarr-secrets
  namespace: htpc
spec:
  type: kv-v2
  mount: kv
  path: htpc/scraparr
  vaultAuthRef: vault-auth
  refreshAfter: 30s
  destination:
    create: true
    name: exportarr-secrets
    overwrite: true
