---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      run: transmission
  template:
    metadata:
      labels:
        run: transmission
    spec:
      containers:
        - name: transmission
          image: linuxserver/transmission:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
              name: webui
              protocol: TCP
            - containerPort: 51413
              name: torrent-tcp
              protocol: TCP
            - containerPort: 51413
              name: torrent-udp
              protocol: UDP
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: transmission
            - name: arr-stack-storage
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: arr-stack-pvc
