apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricebuddy-storage
spec:
  storageClassName: local-path-utils
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
