---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: utils
  namespace: utils
spec:
  entryPoints:
    - websecure
    - websecure-local
  routes:
    - kind: Rule
      match: Host(`nextcloud.my-homelab.party`)
      priority: 0
      middlewares:
        - name: nextcloud-securityheaders
        - name: nextcloud-redirectregex1
        - name: nextcloud-redirectregex2
        - name: nextcloud-compress
      services:
        - kind: Service
          name: nextcloud
          port: 80
    - kind: Rule
      match: Host(`dashy.my-homelab.party`)
      middlewares:
        - name: homelab-auth
      priority: 0
      services:
        - kind: Service
          name: dashy
          port: 4000
