---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radarr
  template:
    metadata:
      labels:
        run: radarr
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox:1.37.0
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/media/movies /data/torrents/radarr && chown -R 1000:1000 /data",
            ]
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /data
              subPath: data
      containers:
        - name: radarr
          image: 11notes/radarr:5.27.5
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "CET"
          resources:
            requests:
              memory: "150Mi"
              cpu: "75m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          ports:
            - containerPort: 7878
              name: webui
          # NOTE: Probes are kept but you may need to adjust the path if you remove the URL base in the app's config.
          # The default for 11notes is '/', not '/radarr/'. This will work after you set the URL base in the new UI.
          startupProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /radarr/etc
              subPath: radarr
            - name: arr-stack-storage
              mountPath: /data
              subPath: data
            - name: tmpfs
              mountPath: /tmp
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: htpc-pvc
        - name: tmpfs
          emptyDir: {}
