---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radarr
  template:
    metadata:
      labels:
        run: radarr
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: check-config-dir
          image: busybox:1.37.0
          command:
            [
              "sh",
              "-c",
              'mkdir -p /config && touch /config/config.xml && echo "<Config><UrlBase>/radarr</UrlBase></Config>" > /config/config.xml',
            ]
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: radarr
        - name: fix-permissions
          image: busybox:1.37.0
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data/media/movies /data/torrents/radarr && chown -R 1000:1000 /data",
            ]
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /data
              subPath: data
      containers:
        - name: radarr
          image: linuxserver/radarr:v5.26.2.10099
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "CET"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          resources:
            requests:
              memory: "150Mi"
              cpu: "75m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          ports:
            - containerPort: 7878
              name: webui
          startupProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /radarr/
              port: 7878
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: radarr
            - name: arr-stack-storage
              mountPath: /data
              subPath: data
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: htpc-pvc
