---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tandoor-credentials
  namespace: utils
spec:
  encryptedData:
    username: AgREPLACE_WITH_KUBESEAL_OUTPUT
    password: AgREPLACE_WITH_KUBESEAL_OUTPUT
    secret-key: AgREPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: tandoor-credentials
      namespace: utils
    type: Opaque
