---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tandoor-credentials
  namespace: utils
spec:
  type: kv-v2
  mount: kv
  path: utils/tandoor
  vaultAuthRef: vault-auth
  refreshAfter: 30s
  destination:
    create: true
    name: tandoor-credentials
    overwrite: true
