---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  # Certificate patch
  - target:
      kind: Certificate
      name: cluster-certificate
      namespace: infra
    patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: cluster-certificate
        namespace: infra
      spec:
        secretName: staging-certificate-secret
  # ClusterIssuer patch
  - target:
      kind: ClusterIssuer
      name: letsencrypt-issuer
    patch: |-
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-issuer
      spec:
        acme:
          server: https://acme-staging-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-staging
