---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  # Certificate patch
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: cluster-certificate
        namespace: infra
      spec:
        secretName: production-certificate-secret
  # ClusterIssuer patch
  - patch: |-
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-issuer
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: letsencrypt-production
