---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homelab-credentials
spec:
  encryptedData:
    users: AgBuJmwKCqWIA7/GW4rp6mtnzy6Muw0eSZykjZ55Z+OqWo1T5GFglnaPGv3fARHQ0jHelk1mwYIGAXHeNW4aH+BqL2MFcpb5g3eW0pDy9WQRlY94uEMVcRXatou0KLFpqbmXPuiOf/+SQpXBkx6eeoc29BwRjWm4GvGxatewPdS/7wQ259cGKhjGhjYpv1F2k0IqyQ5yuunZs5UsypqpoBBeOfK/Nt2yW8ZSLJv0YfR3InRRAYnv3sX3WFVLINzm8KPUqsTxl6LBwU92riZcUDRHzuSYZI2TeNyohS4y7HhfqKKAVry/Ae+MkwuMnbKna731OW5W/M1NW2SrLbhU99ZfjH4WYvPYF1NHdpVqpfSvy8a4GWlLxwo90BSlwSqyLeMM3jrHXFtOltYDEpTeOB1ZklwmUOBmVZafF9N5/a1k1fnps+q2Gb6qKu1prTOhkA/a4V5nMMj2+bav2GYTaW5vVT96hrE4JgC3l/uNIVbSoTwn8SSBNtXOcGCshr5Kd08jvlwrzXQggLnMvmM5+I6x7zCW1Q8BItAib3+59NgV/eHkuyFsyOM8QzvX+bK1lpSEkHeiyTt5rYMA1YTI3dzbQzQHA+qja8KesENL/6nzoPq9Lt+UJ4AM5ETlEAay80VQ7R89eaXyXz2rY+zdLK9j5EqI1IN/HJqjOUTzjz9YiALE4adffE1KVpXifgPlcC+9DdZXXfr+LLejMmFbV6HeKdWBHiYkkSe8c0MlRbIZC+iwMLJ/LwwR2qgXecA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homelab-credentials
    type: Opaque
