---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-credentials
  namespace: infra
spec:
  encryptedData:
    users: AgREPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: homelab-credentials
      namespace: infra
    type: Opaque
