---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: homelab-credentials
  namespace: infra
spec:
  type: kv-v2
  mount: kv
  path: infra/traefik
  vaultAuthRef: vault-auth
  refreshAfter: 30s
  destination:
    create: true
    name: homelab-credentials
    overwrite: true
