---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.8
    releaseName: metallb
    includeCRDs: true
