---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
  namespace: utils
  labels:
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: frontend
      app: actual
  template:
    metadata:
      labels:
        tier: frontend
        app: actual
    spec:
      containers:
        - name: actual
          image: actualbudget/actual-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-data-pvc
