---
apiVersion: v1
kind: Service
metadata:
  name: actual
  labels:
    app: actual
spec:
  selector:
    app: actual
    tier: frontend
  ports:
    - port: 5006
      targetPort: http
      name: http
      protocol: TCP
