---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: flaresolverr
  name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flaresolverr
  template:
    metadata:
      labels:
        run: flaresolverr
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.3.25
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: TZ
              value: "CET"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: LOG_LEVEL
              value: info
            - name: PROMETHEUS_ENABLED
              value: "true"
            - name: PROMETHEUS_PORT
              value: "8192"
          ports:
            - containerPort: 8191
              name: webui
            - containerPort: 8192
              name: metrics
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: flaresolverr
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: htpc-pvc
