apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  type: ClusterIP
  ports:
    - port: 8191
      protocol: TCP
      targetPort: 8191
      name: webui
  selector:
    run: flaresolverr
