---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ingress-route.yaml
  - application.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# patches:
#   - path: server-patch.yaml
#   - path: configmap.yaml
#   - path: deployment.yaml
