kind: ConfigMap
apiVersion: v1
metadata:
  name: tandoor-nginx-config # Renamed for clarity
  labels:
    app: tandoor
data:
  nginx-config: |-
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      server {
        listen 80;
        server_name _;

        client_max_body_size 16M;

        # serve static files
        location /static/ {
          alias /static/;
          expires 1y;
          add_header Cache-Control "public";
        }
        # serve media files
        location /media/ {
          alias /media/;
        }
      }
    }
