---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: recipes
  name: tandoor-nginx-config
  namespace: utils
data:
  nginx.conf: |-
    events {
      worker_connections 1024;
    }
    http {
      include mime.types;
      access_log /dev/stdout;
      error_log /dev/stderr;
      server {
        listen 80;
        server_name _;
        client_max_body_size 50M;

        location /static/ {
            alias /static/;
            expires 1y;
            add_header Cache-Control "public";
        }
        location /media/ {
            alias /media/;
            expires 7d;
            add_header Cache-Control "public";
        }
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
        }
      }
    }
