---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: utils
  labels:
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: recipes
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tandoor-data-pvc
        - name: nginx-config
          configMap:
            name: tandoor-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      initContainers:
        - name: init-tandoor-data
          image: vabene1111/recipes:2.3.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              set -e
              source venv/bin/activate
              echo "Waiting for DB..."
              # Simple wait loop - adjust timeout/check as needed
              timeout=60
              until nc -z $POSTGRES_HOST $POSTGRES_PORT; do
                echo "Waiting for Tandoor DB ($POSTGRES_HOST:$POSTGRES_PORT)..."
                timeout=$((timeout-5))
                if [ $timeout -le 0 ]; then
                  echo "Error: Tandoor DB timed out."
                  exit 1
                fi
                sleep 5
              done
              echo "Tandoor DB is up. Updating database..."
              python manage.py migrate --noinput
              python manage.py collectstatic --noinput
              echo "Setting media/static file ownership and permissions"
              mkdir -p /opt/recipes/mediafiles
              mkdir -p /opt/recipes/staticfiles
              chown -R 65534:65534 /opt/recipes/mediafiles /opt/recipes/staticfiles
              find /opt/recipes/mediafiles -type d -print0 | xargs -0 -r chmod 755
              find /opt/recipes/mediafiles -type f -print0 | xargs -0 -r chmod 644
              find /opt/recipes/staticfiles -type d -print0 | xargs -0 -r chmod 755
              find /opt/recipes/staticfiles -type f -print0 | xargs -0 -r chmod 644
              echo "Done"
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: secret-key
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-db-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: username
            - name: POSTGRES_DB
              value: recipes-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: password
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: data
              mountPath: /opt/recipes/mediafiles
              subPath: media
            - name: data
              mountPath: /opt/recipes/staticfiles
              subPath: static
      containers:
        - name: tandoor-nginx
          image: nginx:1.29.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 700m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /media
              subPath: media
              readOnly: true
            - name: data
              mountPath: /static
              subPath: static
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
        - name: tandoor-app
          image: vabene1111/recipes:2.3.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65534
          command:
            - /opt/recipes/venv/bin/gunicorn
            - -b
            - :8080
            - --access-logfile
            - "-"
            - --error-logfile
            - "-"
            - --log-level
            - INFO
            - recipes.wsgi
          ports:
            - containerPort: 8080
              name: gunicorn
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: gunicorn
              scheme: HTTP
            periodSeconds: 30
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: gunicorn
              scheme: HTTP
            periodSeconds: 30
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /opt/recipes/mediafiles
              subPath: media
            - name: data
              mountPath: /opt/recipes/staticfiles
              subPath: static
          env:
            - name: DEBUG
              value: "0"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: secret-key
            - name: GUNICORN_MEDIA
              value: "0"
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-db-rw
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: username
            - name: POSTGRES_DB
              value: recipes-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: password
            - name: TZ
              value: "CET"
            - name: REDIS_PORT
              value: "6379"
