---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  namespace: utils
  labels:
    app: tandoor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      labels:
        app: tandoor
    spec:
      restartPolicy: Always
      serviceAccount: recipes
      serviceAccountName: recipes
      initContainers:
        - name: init-migrations-and-static
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: secret-key
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: tandoor
            - name: POSTGRES_DB
              value: tandoor
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: postgresql-password
          image: vabene1111/recipes
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
          command:
            - sh
            - -c
            - |
              set -e
              echo "Updating database"
              source venv/bin/activate
              python manage.py migrate --noinput
              echo "Collecting static files"
              python manage.py collectstatic_js_reverse
              python manage.py collectstatic --noinput
              echo "Setting media/static file attributes"
              mkdir -p /opt/recipes/mediafiles /opt/recipes/staticfiles
              chown -R 65534:65534 /opt/recipes/mediafiles /opt/recipes/staticfiles
              find /opt/recipes/mediafiles -type d -exec chmod 755 {} + || true # Allow errors if dir is empty initially
              find /opt/recipes/mediafiles -type f -exec chmod 644 {} + || true
              find /opt/recipes/staticfiles -type d -exec chmod 755 {} + || true
              find /opt/recipes/staticfiles -type f -exec chmod 644 {} + || true
              echo "Done"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: data
              subPath: tandoor/media
            - mountPath: /opt/recipes/staticfiles
              name: data
              subPath: tandoor/static
      containers:
        - name: recipes-nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http-nginx
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /media
              name: data
              subPath: tandoor/media
              readOnly: true
            - mountPath: /static
              name: data
              subPath: tandoor/static
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx-config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
        - name: tandoor
          image: vabene1111/recipes
          imagePullPolicy: IfNotPresent
          command:
            - /opt/recipes/venv/bin/gunicorn
            - -b
            - :8080
            - --access-logfile
            - "-"
            - --error-logfile
            - "-"
            - --log-level
            - INFO
            - recipes.wsgi
          ports:
            - containerPort: 8080
              name: gunicorn
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/version/
              port: gunicorn
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/version/
              port: gunicorn
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: DEBUG
              value: "0"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: secret-key
            - name: DB_ENGINE
              value: django.db.backends.postgresql
            - name: POSTGRES_HOST
              value: tandoor-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: tandoor
            - name: POSTGRES_DB
              value: tandoor
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: postgresql-password
            - name: STATIC_ROOT
              value: /opt/recipes/staticfiles
            - name: MEDIA_ROOT
              value: /opt/recipes/mediafiles
            - name: STATIC_URL
              value: /static/
            - name: MEDIA_URL
              value: /media/
          volumeMounts:
            - mountPath: /opt/recipes/mediafiles
              name: data
              subPath: tandoor/media
            - mountPath: /opt/recipes/staticfiles
              name: data
              subPath: tandoor/static
              readOnly: true
          securityContext:
            runAsUser: 65534
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: utils-pvc
        - name: nginx-config
          configMap:
            name: recipes-nginx-config
            items:
              - key: nginx-config
                path: nginx-config
