---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - deployment.yaml
  - service.yaml
  - service-db.yaml
  - postgres-statefulset.yaml
  - configmap.yaml
  - secret
  - serviceaccount.yaml

commonLabels:
  app: recipes
