---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - deployment.yaml
  - service.yaml
  - postgres-cluster.yaml
  - configmap.yaml
  - serviceaccount.yaml

commonLabels:
  app: recipes
