apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: recipes
  namespace: utils
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      tier: frontend
  podMetricsEndpoints:
    - port: gunicorn
      path: /metrics
