---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-db
  namespace: utils
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  bootstrap:
    initdb:
      # The owner specified here will have credentials generated in the '<cluster-name>-app' secret
      database: recipes
      owner: recipes

  storage:
    storageClass: local-path-utils
    size: 5Gi

  backup:
    retentionPolicy: "30d"
    volumeSnapshot:
      className: local-path-utils
      snapshotOwnerReference: "cluster"
