---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tandoor-db
  namespace: utils
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"

  # Remove managed roles - let CNPG create the standard '-app' secret for the owner
  # managed:
  #   roles:
  #     - name: recipes
  #       login: true
  #       passwordSecret:
  #         name: tandoor-credentials
  #         key: postgresql-password

  bootstrap:
    initdb:
      # The owner specified here will have credentials generated in the '<cluster-name>-app' secret
      database: recipes
      owner: recipes

  storage:
    storageClass: local-path-utils
    size: 5Gi

  backup:
    retentionPolicy: "30d"
    volumeSnapshot:
      className: local-path-utils
      snapshotOwnerReference: "cluster"
