---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recipes-postgresql
  labels:
    app: recipes
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes
      tier: database
  serviceName: recipes-postgresql
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: tandoor-pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: data
      labels:
        app: recipes
        tier: database
    spec:
      securityContext:
        fsGroup: 1001
      serviceAccountName: recipes
      initContainers:
        - name: init-chmod-data
          image: docker.io/bitnami/minideb:stretch
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              mkdir -p /bitnami/postgresql/data
              chmod 700 /bitnami/postgresql/data
              chown -R 1001:1001 /bitnami/postgresql
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: tandoor-pg-data
      containers:
        - name: tandoor-db
          image: docker.io/bitnami/postgresql
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: POSTGRESQL_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_VOLUME_DIR
              value: /bitnami/postgresql
            - name: PGDATA
              value: /bitnami/postgresql/data
            - name: POSTGRES_USER
              value: recipes
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: postgresql-password
            - name: POSTGRESQL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tandoor-credentials
                  key: postgresql-postgres-password
            - name: POSTGRES_DB
              value: recipes
          ports:
            - containerPort: 5432
              name: postgresql
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U "postgres" -d "recipes" -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - -e
                - |
                  pg_isready -U "postgres" -d "recipes" -h 127.0.0.1 -p 5432
                  [ -f /bitnami/postgresql/data/postmaster.pid ]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: tandoor-pg-data
