apiVersion: v1
kind: Service
metadata:
  name: recipes-postgresql
  labels:
    app: recipes
    tier: database
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    app: recipes
    tier: database
