apiVersion: v1
kind: Service
metadata:
  name: recipes
  labels:
    app: recipes
spec:
  selector:
    app: recipes
  ports:
    - port: 80
      targetPort: http
      name: http
      protocol: TCP
    - port: 8080
      targetPort: gunicorn
      name: gunicorn
      protocol: TCP
