---
apiVersion: v1
kind: Service
metadata:
  name: tandoor
  namespace: utils
spec:
  selector:
    app: tandoor
    tier: frontend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tandoor-postgresql
  namespace: utils
spec:
  selector:
    app: tandoor
    tier: database
  ports:
    - port: 5432
      targetPort: postgresql
