apiVersion: v1
kind: Service
metadata:
  name: tandoor-postgres # Renamed
  labels:
    app: tandoor # Updated label
    tier: database
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
  selector:
    app: tandoor # Updated selector
    tier: database
