fullnameOverride: stirling-pdf

envs:
  - name: SECURITY_ENABLELOGIN
    value: "false"

persistence:
  enabled: true
  storageClass: local-path-utils
  size: 8Gi
  path: /configs

probes:
  liveness:
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 15
    timeoutSeconds: 5

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

deployment:
  extraVolumeMounts:
    - name: storage-volume
      mountPath: /configs

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
