---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

helmCharts:
  - name: authentik
    repo: https://charts.goauthentik.io
    version: 2025.4.1
    releaseName: authentik
    includeCRDs: true
    valuesFile: values.yaml
