---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.5

namespace: argocd

resources:
- namespace.yaml
- application.yaml
- configmap.yaml
- ingress-route.yaml
- presync-rbac.yaml
- presync-hook.yaml
- server-patch.yaml

patchesStrategicMerge:
- server-patch.yaml
