apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.5

resources:
  - application.yaml
  - ingress-route.yaml

patches:
  - path: server-patch.yaml
  - path: deployment.yaml
  - path: argocd-cm-patch.yaml
