apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.5

namespace: argocd

resources:
  - namespace.yaml
  - application.yaml
  - ingress-route.yaml
  - presync-rbac.yaml
  - presync-hook.yaml

patches:
  - path: server-patch.yaml
    target:
      kind: Deployment
      name: argocd-server
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data
        value:
          kustomize.buildOptions: --enable-helm
