---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-decrypt-secrets
  namespace: htpc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-decryptor
  namespace: htpc
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-decrypt-secrets
  namespace: htpc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-decryptor
subjects:
  - kind: ServiceAccount
    name: argocd-decrypt-secrets
    namespace: htpc