---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-decrypt-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-decryptor
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-decrypt-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-decryptor
subjects:
  - kind: ServiceAccount
    name: argocd-decrypt-secrets
    namespace: htpc
