apiVersion: batch/v1
kind: Job
metadata:
  name: presync-decrypt-secrets
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: argocd-decrypt-secrets
      containers:
        - name: decrypt-secrets
          image: mozilla/sops:v3.7.3
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              SOPS_AGE_KEY_FILE=/keys/keys.txt
              AGE_PUBLIC_KEY=$(grep -oP "public key: \K(.*)" "$SOPS_AGE_KEY_FILE")
              kubectl get secrets -n htpc -o json | jq -r '.items[] | select(.data | to_entries[] | select(.value | contains("BEGIN AGE ENCRYPTED FILE"))) | .metadata.name' | while read -r secret_name; do
                echo "Decrypting secret: $secret_name"
                kubectl get secret $secret_name -n htpc -o yaml | sops --decrypt --age "$AGE_PUBLIC_KEY" --encrypted-regex '^(data|stringData)$' --in-place "$file" | kubectl apply -f -
              done
          volumeMounts:
            - name: argocd-home
              mountPath: /argo
            - name: sops-key
              mountPath: /keys
      restartPolicy: Never
      volumes:
        - name: argocd-home
          hostPath:
            path: /opt/argocd
            type: DirectoryOrCreate
        - name: sops-key
          hostPath:
            path: /home/chaitanya2692
            type: Directory
  backoffLimit: 3