---
apiVersion: v1
kind: Service
metadata:
  name: crossseed
spec:
  type: ClusterIP
  ports:
    - port: 2468
      protocol: TCP
      targetPort: 2468
      name: http
  selector:
    run: crossseed
