---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich
spec:
  schedule: "11 12 3 * * *"
  backupOwnerReference: self
  method: volumeSnapshot
  cluster:
    name: immich
