---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - secret
  - backup.yaml
  - postgres-cluster.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.9.3
    releaseName: immich
    includeCRDs: true
    valuesFile: values.yaml
