---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - secret
  - backup.yaml
  - postgres-cluster.yaml

helmCharts:
  - name: immich
    repo: https://immich-app.github.io/immich-charts
    version: 0.9.2
    releaseName: immich
    includeCRDs: true
    valuesFile: values.yaml
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.23.2
    releaseName: cloudnative-pg
    includeCRDs: true
    valuesInline:
      config:
        clusterWide: false
