apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
  labels:
    type: immich
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cluster-storage
  hostPath:
    path: /opt/cluster/utils/immich
    type: DirectoryOrCreate
