apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: utils
spec:
  imageName: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvector0.8.1-pgvectors0.3.0
  instances: 1

  # postgresql:
  #   shared_preload_libraries:
  #     - "vectors.so"

  enableSuperuserAccess: true

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: immich-db
      owner: immich
      secret:
        name: immich-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    storageClass: local-path-utils
    size: 20Gi

  backup:
    volumeSnapshot:
      className: local-path-utils
      snapshotOwnerReference: "cluster"
    retentionPolicy: "30d"
