apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: utils
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.5-v0.3.0@sha256:be3f025d79aa1b747817f478e07e71be43236e14d00d8a9eb3914146245035ba
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  # enableSuperuserAccess: true

  managed:
    roles:
      - name: immich
        superuser: true
        login: true
        # passwordSecret:
        #   name: immich-credentials

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-credentials
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    storageClass: local-path-utils
    size: 20Gi

  backup:
    volumeSnapshot:
      className: local-path-utils
      snapshotOwnerReference: "cluster"
    retentionPolicy: "30d"
