apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: utils
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.4
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  enableSuperuserAccess: true

  managed:
    roles:
      - name: immich
        superuser: true
        login: true
        passwordSecret:
          name: immich-credentials

  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    storageClassName: longhorn-utils
    size: 20Gi

  backup:
    volumeSnapshot:
      className: longhorn
      snapshotOwnerReference: "cluster"
    retentionPolicy: "30d"
