---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jellyfin
  name: jellyfin
spec:
  selector:
    matchLabels:
      run: jellyfin
  template:
    metadata:
      labels:
        run: jellyfin
    spec:
      containers:
        - env:
            - name: TZ
              value: CET
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/jellyfin
          imagePullPolicy: IfNotPresent
          name: jellyfin
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: htpc-home
              subPath: jellyfin
            - mountPath: /tv
              name: htpc-home
              subPath: media/tv
              readOnly: true
            - mountPath: /movies
              name: htpc-home
              readOnly: true
              subPath: media/movies
