---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  labels:
    app: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy:latest
        ports:
        - containerPort: 4000
        env:
        - name: TZ
          value: "CET"
        - name: PORT
          value: "4000"
        volumeMounts:
        - name: dashy-config
          mountPath: /app/public/conf.yml
          subPath: conf.yml
      volumes:
      - name: dashy-config
        configMap:
          name: dashy-config
