{
 "title": "HTPC dashboard",
 "tags": [ "htpc" ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Jellyfin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jellyfin CPU limits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"jellyfin\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"jellyfin\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"jellyfin\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"jellyfin\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Limits"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"jellyfin\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"jellyfin\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"jellyfin\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"jellyfin\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Limits"
    }
   ]
  },
  {
   "title": "Memory p90 recommendation (bytes) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(container_memory_working_set_bytes{namespace=\"htpc\", container=\"jellyfin\"})[7d:5m]) * 1.15 / 1073741824",
     "legendFormat": "Requestsed Memory"
    }
   ]
  },
  {
   "title": "CPU p90 recommendation (cores) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"jellyfin\"}[5m]))[7d:5m]) * 1.15",
     "legendFormat": "Requestsed CPU"
    }
   ]
  },
  {
   "title": "Jellyfin Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({instance=\"htpc/jellyfin-7d4bd47759-ctn74:jellyfin\"}  | detected_level = `error` != \"MediaBrowser.MediaEncoding.Encoder.MediaEncoder\"[$__auto]))"
    }
   ]
  },
  {
   "title": "Jellyfin Error Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"htpc/jellyfin-7d4bd47759-ctn74:jellyfin\"} | detected_level = `error` != \"MediaBrowser.MediaEncoding.Encoder.MediaEncoder\""
    }
   ]
  },
  { "title": "Radarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Radarr CPU limits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"radarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"radarr\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"radarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"radarr\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Limits"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"radarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"radarr\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"radarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"radarr\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Limits"
    }
   ]
  },
  {
   "title": "Memory p90 recommendation (bytes) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(container_memory_working_set_bytes{namespace=\"htpc\", container=\"radarr\"})[7d:5m]) * 1.15 / 1073741824",
     "legendFormat": "Requestsed Memory"
    }
   ]
  },
  {
   "title": "CPU p90 recommendation (cores) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"radarr\"}[5m]))[7d:5m]) * 1.15",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Radarr Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({instance=\"htpc/radarr-5654678f79-pldzd:radarr\"} | detected_level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "Radarr Error Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"htpc/radarr-5654678f79-pldzd:radarr\"} | detected_level = `error`"
    }
   ]
  },
  { "title": "Sonarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Sonarr CPU limits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"sonarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"sonarr\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"sonarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"sonarr\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Limits"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"sonarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"sonarr\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"sonarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"sonarr\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Limits"
    }
   ]
  },
  {
   "title": "Memory p90 recommendation (bytes) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(container_memory_working_set_bytes{namespace=\"htpc\", container=\"sonarr\"})[7d:5m]) * 1.15 / 1073741824",
     "legendFormat": "Requestsed Memory"
    }
   ]
  },
  {
   "title": "CPU p90 recommendation (cores) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"sonarr\"}[5m]))[7d:5m]) * 1.15",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Sonarr Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({instance=\"htpc/sonarr-7b5b64b874-5f9bj:sonarr\"} | detected_level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "Sonarr Error Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"htpc/sonarr-7b5b64b874-5f9bj:sonarr\"} | detected_level = `error`"
    }
   ]
  },
  { "title": "Prowlarr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Prowlarr CPU limits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"prowlarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"prowlarr\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"prowlarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"prowlarr\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Limits"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"prowlarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"prowlarr\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"prowlarr\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"prowlarr\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Limits"
    }
   ]
  },
  {
   "title": "Memory p90 recommendation (bytes) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(container_memory_working_set_bytes{namespace=\"htpc\", container=\"prowlarr\"})[7d:5m]) * 1.15 / 1073741824",
     "legendFormat": "Requestsed Memory"
    }
   ]
  },
  {
   "title": "CPU p90 recommendation (cores) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"prowlarr\"}[5m]))[7d:5m]) * 1.15",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Prowlarr Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({instance=\"htpc/prowlarr-7975456d6-ckhwl:prowlarr\"} | detected_level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "Prowlarr Error Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"htpc/prowlarr-7975456d6-ckhwl:prowlarr\"} | detected_level = `error`"
    }
   ]
  },
  { "title": "Transmission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Transmission CPU limits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"transmission\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"transmission\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"transmission\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"transmission\", resource=\"cpu\"}))",
     "legendFormat": "CPU Utilization from Limits"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"transmission\"}[5m])) * 100) / (sum(kube_pod_container_resource_requests{namespace=\"htpc\", container=\"transmission\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Requests"
    },
    {
     "expr": "(sum(rate(container_memory_working_set_bytes{namespace=\"htpc\", container=\"transmission\"}[5m])) * 100) / (sum(kube_pod_container_resource_limits{namespace=\"htpc\", container=\"transmission\", resource=\"memory\"}))",
     "legendFormat": "Memory Utilization from Limits"
    }
   ]
  },
  {
   "title": "Memory p90 recommendation (bytes) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(container_memory_working_set_bytes{namespace=\"htpc\", container=\"transmission\"})[7d:5m]) * 1.15 / 1073741824",
     "legendFormat": "Requestsed Memory"
    }
   ]
  },
  {
   "title": "CPU p90 recommendation (cores) with 15% margin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, sum(rate(container_cpu_usage_seconds_total{namespace=\"htpc\", container=\"transmission\"}[5m]))[7d:5m]) * 1.15",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Transmission Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({instance=\"htpc/transmission-56c48684bf-pxrwj:transmission\"} | detected_level = `error` [$__auto]))"
    }
   ]
  },
  {
   "title": "Transmission Error Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"htpc/transmission-56c48684bf-pxrwj:transmission\"} | detected_level = `error`"
    }
   ]
  }
 ]
}