apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 61.4.0
    releaseName: kube-prometheus-stack
    namespace: infra
    valuesFile: values-kube-prometheus-stack.yaml

  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 7.1.0
    releaseName: loki
    namespace: infra
    valuesFile: values-loki.yaml

  - name: jaeger
    repo: https://jaegertracing.github.io/helm-charts
    version: 3.4.1
    releaseName: jaeger
    namespace: infra
    valuesFile: values-jaeger.yaml
