apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: loki
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
