apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: traefik
  endpoints:
    - port: web
      path: /metrics
      interval: 30s
