---
config:
  clients:
    - url: http://loki.infra.svc.cluster.local:3100/loki/api/v1/push

extraVolumes:
  - name: promtail-positions-vol
    persistentVolumeClaim:
      claimName: promtail-positions-pvc
extraVolumeMounts:
  - name: promtail-positions-vol
    mountPath: /data

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
