---
config:
  clients:
    - url: http://loki.infra.svc.cluster.local:3100/loki/api/v1/push
  positions:
    filename: /data/positions.yaml

persistence:
  enabled: true
  existingClaim: promtail-positions-pvc

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 2Gi
