---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: protonvpn-wireguard
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgCyB/bw55CVxYo0YROC1Fp5IXbh5dKX8kXK++682FIPhOPYOKl5hu31fUALokmcKKKjvqRjL0SA96Z5w/78vJme60w04b4veE2hEZriicSX45UCZnVUjugQZWmzv4grEu7VaztRtvxp5embt5+GvfNpxyhVXiHFLUJwrIbylaae9ET4VoeWDxcl80kKx6h4+fBcSr8Afzezsz1CnNT1tNpzPSe0LRXnj/r8k6Ld9eqvHa3Q2uGvTpcKcDQKGB/FrnMqSOKoAFFTj5AG9DPFM3zLlwyPQ0+QRRtv0q23mB2PQ9AkTH3axNXGfSpuwMSC8nGeu9rLaezWq2ci90dBc8ejZgKBCgQY9pN+wYIq4Gc2Uth8j9bfu/UGRfQ77mcYuQdTvei4NYtoRI9dggZel6rrsAZFqN225CcNEouignrYjwZc4FmB+UOY+Wyy0YfuS4i7pNlq6Cfx+stdvyTQNCOkh2EM/OhvukG9Moq632xorxU1hipfOE+hbGGkZO3KboXn5Gpm9yzqbSoZb6XGrwlIvzR0WrbKkKbRgqk9OXKLRxm+IvhoaZA4+YwBLgioVefUQTLhHwtlKHtNHihIVXsB9YkPkWSoVIFGn7LSzlofUnWOjsvuKw7QOfTOwYZAjAXRuT7GU5LAGjEyt0JSBiAVW24nDHTtt47SmhdMKCO3bgH1fC16b9WOSSS1VpMdSYbE78n9WPVqEB2SEZ326vMHLi/K8G6kgC0FjwjFh3stVaLHkWGiN58m75ZvKA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: protonvpn-wireguard
