---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: TZ
              value: "CET"
          volumeMounts:
            - name: config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
              readOnly: true
            - name: config
              mountPath: /app/config/services.yaml
              subPath: services.yaml
              readOnly: true
            - name: config
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
              readOnly: true
            - name: config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: config
          configMap:
            name: homepage-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
