---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: homepage-config
    files:
      - settings.yaml
      - services.yaml
      - widgets.yaml
      - kubernetes.yaml

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: homepage
