---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utils

resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: homepage
