---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: homepage-auth
spec:
  encryptedData:
    HOMEPAGE_AUTH_PASSWORD: AgCyQ8YbLMmtN45zXcsGXeR31OU+j6vCv4cPPX9+MJinsn8Ihk0/E0TiQvcgz0+fiKYFWgHDOPvm6vTm5R6i+z2uVy7GqiVyqIaKak4XqerUytgzO8XlOZ5LRJg3aFGfri/uCNVye9pI0F4O7zSQxQHondlJacfstrGUlTe0mfCfPouEKmUKguUhzGaKb6dP6Z9OVCMXdzzppJgcHKEDS3HhpGTHNq8QuVcJBTqF0y6fM9fuUK3nSWRiVOrIAIpU3WWlFzbARSRl5vslVC1BK6RIi8+pmf53SMbcbihMwmVKYAHfYtwuN+BcopKAaKq7zlgu1+wo3B8ArOangZHrKZwtUwblTYryjLjthXbTlcgGSRY6iyupkDfkMQ+zU32n/CJIifrRoOSOuMC1vTBU3RY462LbhWOdO25dE36MDqGHkVwsp/j0i5DP9G8o0WaT/YFSyg3y/bby4h+V79Qp1ba3YiFA4Ip0mworgcBMX8ot7aMb00p03bJca9KBYK1MoizvvSqAo3AEKOKrQT/+wy0LBmS9U4H/4Dkqa8D0nhV1hCEYkoexCAnVdR1GluQ1lzNZiE/XuXlBes1csTOT2T3TirB/Nf8n1/6VIu4pdD0oe5E/R/hoO02jsNDPLKv+ZRyULh5id11ET1RYrir5CUsU7bkVRww9BpEQeeNfiRQN1clci41sgJikUiqgdEB4ruM1jPlnA4POcoFrUQybtOA=
    HOMEPAGE_AUTH_SECRET: AgBu6bE2g99oefOy4QkuUvEoDJ9eCegV0zFz6O19eE0LO4lbxpcROhAETV98lspy1XJLK9cPLt5wq91I1+U+TOITiFaWtgjhdQnH5nEzWyREErVDyTtcLvlgstozX1K2wwgUpZ+1RrxjXXKpG0taTub9fWiFUp35w5VZtjnKJgFCkfM86aC9Io8/sw+xbqOU3gf0x1hai0GnG5aaxzdKFeeiYhacIXekVIkY5ViQB00p9tyhWdsZMrsloAIzLjILcW+RDz3IPW2yQOgE7qpgfis19bAXyonA0LpxyJ3z+eDnR/S6oNXW4SjRD1WInedQnbHmvyK/gyB5ZPsXPOu7nRWtu0w79MSwO1pgopQDtyuT8k2T9tcSuKyCfHIFbXgV8zpYAyU89BVICocJlDqwPebxVkZURHk95A0ZyFfIBAw58JSN4vC4z6kQhwkj5cd/JT5DJ0qSBNHjP/6tB60EyeuxLbC/2qoQRf9TRSF2hFw3Dd1LqEj4yDHnvMwceKnwXZB/9qVlTHIB3LQ0aiKnR7bUx56EXOYlbbxxXWk4fuxR3k/mYYkFAhTAeP2rIqfObdozx9sbgznJoUF5TPAXnT9+ssEpgTR76CFpACHaBCR8fr+CBop4TpTJUXT6VBjHfPyPYRLalVbK+E0BHzjhxb2IAV3CWT+fKZZ/GH/tCf/gfvN6X7xvEMh3Twp2QJFjN7deotekpL2ATwPy4R5MeAr9ujr5M+O5byP8ewF5yQv2uFwEExa0FzrszvwFWQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: homepage-auth
    type: Opaque
