---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: infra
  namespace: infra
spec:
  tls:
<<<<<<< HEAD
    secretName: staging-certificate-secret
=======
    secretName: staging-certificate
>>>>>>> 09ff2bf (Initial commit)
