---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-credentials
  namespace: utils
spec:
  encryptedData:
    DB_USERNAME: AgREPLACE_WITH_KUBESEAL_OUTPUT
    DB_PASSWORD: AgREPLACE_WITH_KUBESEAL_OUTPUT
    username: AgREPLACE_WITH_KUBESEAL_OUTPUT
    password: AgREPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: immich-credentials
      namespace: utils
    type: Opaque
