---
apiVersion: v1
kind: Secret
metadata:
    name: immich-credentials
    namespace: utils
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:DNDbOucHNT26CA==,iv:CYvg1EItiNTCHbjKVbrRJzPj5tHK1vg7XzoIix2c9VU=,tag:pedS6r1dHChhbTudyxtBwA==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:zpajK/l04c7j8AyR,iv:lGmN7WqRebWOBQlItjxvZqB4PktmW8SOq9Z6y2boG3M=,tag:q7hngx29T6h9aXMLqws+5g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:3ZeML7Lss2jWPN5KQx+3,iv:kVF/EBvZBD9SG6peQJ4yupGNLq7wONGn/8yPTWoUjHE=,tag:qC3AFHddguUSJv7RaccRRQ==,type:str]
    username: ENC[AES256_GCM,data:dOeg4nk=,iv:VjLzS2RzCfW49gDy4tOCBW/e92+r+30Yd9er2Q46C4g=,tag:jfMg+puMazMmhyYQqN7cjQ==,type:str]
    password: ENC[AES256_GCM,data:S9kvtHex7YskIsBcL7jH,iv:qzCB4qElGkKtPP8pyyrlOFVLi/28+4SpTRg1zOpBLao=,tag:1PKWV82wErKsF3mCPEh/Ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfvx83fvk6fzm2hql7a0gq0k4w5q4d0y623fxcw23u3zr0vqzdesl73e43
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVXFRczJKRlc0eWhKMHNL
              YVhNODFod1F3eHV0Q2lXNzlXQ1ZzM0hyK1NzCk56dlhxZjY1SXV0MDg2TmRGUzcx
              ZndkelV4azFkQ0NYZWdhQ1pONnNBK3MKLS0tIHRvZS9Jc1BCSThZaTkydk85WUht
              dEhSdlZGUlpyb3RyOXM3eERXYklrdGcK5td4+1eDgM9wd/37mBKrehMGG2CKKGIx
              0AF0q5JWf7APnS2uyn+NxVCO5z5WCPaHP9b1gYL+b6FVv46ivct19w==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-27T21:50:11Z"
    mac: ENC[AES256_GCM,data:APtzUXhnhCJXNuXFwvWlCFjULd02UPARSY7vdQMDULvgQqajXFTyyjA5uvYOTkfUMJOg8/JZ3w8fCPo7/wCAvGpNO8FRzzqJFu2VMjPfMA45hLnRfak89Kk9UxM2UhZ4FvGy8D7tl3V2bjWi0XpYzWcKVNMOYzhlAnnr3kFKdtE=,iv:PjxF1Vrskx18RY7cQ/GGxVBTemiV88mRIK2ZfjnFNoQ=,tag:7SiWFl2sDfYnbLmPTuKDGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
