---
apiVersion: v1
kind: Secret
metadata:
    name: immich-credentials
    namespace: utils
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:E//7Cv7W,iv:zknKiLD6UEw2SYreuWfJa90NeY9xp0InYlSJAAwV9l8=,tag:tgx+5y3CArpQdlwTVuLe3Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:yjUkEGk5Wn9b+4s=,iv:nQkti15RGidLIXqDp88G28RAQj5ixcutbVWS3btxxWM=,tag:jVK555NyksI3mfNeO6nTsA==,type:str]
    username: ENC[AES256_GCM,data:QU9Cu1DR,iv:/wxf2mzBFQTYaMksmGT1uP7g+UyX2jsrXnYJghmBD4w=,tag:erDSrZuoP+tc2pacYWJjMQ==,type:str]
    password: ENC[AES256_GCM,data:qgHfJOf5R0kJlFo=,iv:2GIePJbbwCWPapRejRcCBBC61nO5ft51ZoRv5p80CWU=,tag:wwEMSAxhdzWfH/RJKPAdDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nfvx83fvk6fzm2hql7a0gq0k4w5q4d0y623fxcw23u3zr0vqzdesl73e43
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUHgrLyt2ZTl5NHA5endv
              R3hzZXRVY0JyTTEvaWJvSW13TEtHTUJleEdrCkZFcFdqSnhaQnREWVBobGdjRnVq
              ZXZwekEzdytpOUNhdWM4ZXUwSkYxbncKLS0tIDZVV2x6Z0NHSThUc0JOZjZJUjdC
              alNGSkJVejBvSE5VQ01DdVkvVkpHYzgKoqrOn44wHEyOKEpBqtbvfQp85WNYfoPk
              DljOoEG5Kg14MmyWbgQUklPsq0tlsOFzLjkm8aO5KfHHZSd1MGaIfQ==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T07:42:34Z"
    mac: ENC[AES256_GCM,data:PD2FHBsqn5YRLxIzzHPsfGpkzQrLh8UTJXF8KJJliTsAggQ1/qn258U4/2yz4HtgPJhou9JGO3Kn5Ql1ixYPkrw/AdMS2Lb1TwnJVzkdoI7TFrkLM5+MlHjt5xCABSc6s/7C49Qsu1zPmMzTgc/SlH5oA1MDhmmQR/GG6D9u8X0=,iv:MZcMEi7Jx1QDTxR//kZJQ8DJFS3bB733YPlN/1Co91k=,tag:voFYB2FpU0OfqBG5ufvS/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
