---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
data:
  conf.yml: |
    pageInfo:
      title: "Dashy"
      description: "Welcome to your new dashboard!"
      navLinks:
        - title: "GitHub"
          path: "https://github.com/Lissy93/dashy"
        - title: "Documentation"
          path: "https://dashy.to/docs"
    appConfig:
      theme: "one-dark"
      layout: "auto"
      iconSize: "medium"
    sections:
      - name: "Home Theater"
        icon: "fas fa-play-circle"
        items:
          - title: "Jellyfin"
            description: "Media Server"
            icon: https://www.google.com/s2/favicons?domain=https://jellyfin.org/&sz=256
            url: "https://jellyfin.my-homelab.party"
          - title: "Sonarr"
            description: "TV Show Manager"
            icon: https://www.google.com/s2/favicons?domain=https://sonarr.tv/&sz=256
            url: "https://sonarr.my-homelab.party"
          - title: "Radarr"
            description: "Movie Manager"
            icon: https://www.google.com/s2/favicons?domain=https://radarr.video/&sz=256
            url: "https://radarr.my-homelab.party"
          - title: "Prowlarr"
            description: "Torrent Indexer"
            icon: https://raw.githubusercontent.com/NX211/homer-icons/refs/heads/master/svg/prowlarr.svg
            url: "https://prowlarr.my-homelab.party"
          - title: "Transmission"
            description: "Torrent Client"
            icon: https://www.google.com/s2/favicons?domain=https://transmissionbt.com/&sz=256
            url: "https://transmission.my-homelab.party"
      - name: "Infrastructure"
        icon: "fas fa-network-wired"
        items:
          - title: "Traefik"
            description: "Reverse Proxy"
            icon: https://djeqr6to3dedg.cloudfront.net/repo-logos/library/traefik/live/logo-1720462302224.png
            url: "https://traefik.my-homelab.party"
      - name: "Storage"
        icon: "fas fa-cloud"
        items:
          - title: "Nextcloud"
            description: "File browser and more"
            icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/refs/heads/main/svg/nextcloud-white.svg
            url: "https://nextcloud.my-homelab.party"
