# File: base/utils/dashy/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: dashy
  name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dashy
  template:
    metadata:
      labels:
        run: dashy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9200"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: TZ
              value: "CET"
            - name: PORT
              value: "4000"
          volumeMounts:
            - name: dashy-config
              mountPath: /app/user-data/conf.yml
              subPath: conf.yml
            - name: dashy-data
              mountPath: /app/user-data
      volumes:
        - name: dashy-data
          persistentVolumeClaim:
            claimName: dashy-data-pvc
        - name: dashy-config
          configMap:
            name: dashy-config
