---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc


resources:
  - namespace.yaml
  - jackett
  - radarr
  - sonarr
  - bazarr
  - transmission
  - jellyfin
  - cert-manager
  - traefik
  - metallb
  - ingress-route.yaml


vars:
  - name: SONARR
    objref:
      apiVersion: v1
      kind: Service
      name: sonarr
  - name: RADARR
    objref:
      apiVersion: v1
      kind: Service
      name: radarr

labels:
  - includeSelectors: true
    pairs:
      app: htpc

patches:
  - path: volumes_patch.yaml
  - path: env.yaml
