---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

commonLabels:
  app: htpc

resources:
  - jackett
  - radarr
  - sonarr
  - bazarr
  - transmission
  - jellyfin
  - home-assistant
  - ingress-route.yaml

patchesStrategicMerge:
  - volumes_patch.yaml
  - env.yaml

vars:
  - name: SONARR
    objref:
      kind: Service
      name: sonarr
      apiVersion: v1
  - name: RADARR
    objref:
      kind: Service
      name: radarr
      apiVersion: v1
