---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
<<<<<<< HEAD
  - namespace.yaml
  - prowlarr
  - radarr
  - sonarr
  - transmission
  - jellyfin
  - cert-manager
  - traefik
  - metallb
  - nextcloud
  - flaresolverr
  - dashy
  - ingress-route.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - storageclass.yaml
=======
  - htpc
  - infra
  - utils
  - cluster
>>>>>>> 09ff2bf (Initial commit)

configMapGenerator:
  - name: global-env
    literals:
      - TZ=CET

vars:
  - name: SONARR
    objref:
      apiVersion: v1
      kind: Service
      name: sonarr
  - name: RADARR
    objref:
      apiVersion: v1
      kind: Service
      name: radarr

labels:
  - includeSelectors: true
    pairs:
      app: htpc

images:
  - name: linuxserver/prowlarr
    newTag: latest
  - name: linuxserver/sonarr
    newTag: latest
  - name: linuxserver/radarr
    newTag: latest
  - name: linuxserver/transmission
    newTag: latest
