---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-pv
  labels:
    type: arr-stack
spec:
  storageClassName: cluster-storage
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/htpc/arr-stack
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    type: nextcloud
spec:
  storageClassName: cluster-storage
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/htpc/nextcloud
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: utils-pv
  labels:
    type: utils
spec:
  storageClassName: cluster-storage
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/htpc/utils
    type: DirectoryOrCreate
