---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-stack-pv
  labels:
    type: arr-stack
spec:
  storageClassName: usb-storage
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/usb/htpc/arr-stack
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
  labels:
    type: nextcloud
spec:
  storageClassName: usb-storage
  capacity:
    storage: 14Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/usb/htpc/nextcloud
    type: DirectoryOrCreate
