---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-stack-pvc
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
  selector:
    matchLabels:
      type: arr-stack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
  selector:
    matchLabels:
      type: nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: utils-pvc
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 14Gi
  selector:
    matchLabels:
      type: utils
