---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      kind: IngressRoute
    patch: |-
      ---
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: ingressroute
        annotations:
          kubernetes.io/ingress.class: traefik-external
      spec:
        tls:
          secretName: staging-certificate-secret
