---
apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9091
      targetPort: 9091
    - name: tcp
      port: 51413
      targetPort: 51413
    - name: udp
      port: 51413
      protocol: UDP
      targetPort: 51413
  selector:
    run: transmission
