---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jellyfin
  name: jellyfin
spec:
  selector:
    matchLabels:
      run: jellyfin
  template:
    metadata:
      labels:
        run: jellyfin
    spec:
      # initContainers:
      #   - name: fix-permissions
      #     image: busybox
      #     command: ["sh", "-c", "chown -R 911:911 /data/media"]
      #     volumeMounts:
      #       - name: arr-stack-storage
      #         mountPath: /data/media
      #         subPath: media
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "CET"
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 8920
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: jellyfin/config
            - name: arr-stack-storage
              mountPath: /data/media
              subPath: data/media
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: htpc-pvc
