---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sonarr
  template:
    metadata:
      labels:
        run: sonarr
    spec:
      initContainers:
        - name: check-config-dir
          image: busybox
          command: ['sh', '-c', 'mkdir -p /config && touch /config/config.xml && echo "<Config><UrlBase>/sonarr</UrlBase></Config>" > /config/config.xml']
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: sonarr
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /tv && chown -R 911:911 /tv"]
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /tv
              subPath: media/tv
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8989
              name: webui
          startupProbe:
            httpGet:
              path: /sonarr/
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /sonarr/
              port: 8989
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /sonarr/
              port: 8989
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          volumeMounts:
            - name: arr-stack-storage
              mountPath: /config
              subPath: sonarr
            - name: arr-stack-storage
              mountPath: /tv
              subPath: media/tv
            - name: arr-stack-storage
              mountPath: /downloads
              subPath: downloads
      volumes:
        - name: arr-stack-storage
          persistentVolumeClaim:
            claimName: arr-stack-pvc
