---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: infra
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"ubuntu",
          "paths": [
            "/opt/cluster/htpc",
            "/opt/cluster/infra",
            "/opt/cluster/utils"
          ]
        }
      ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox:1.36.1
