---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: infra
data:
  config.json: |-
    {
      "nodePathMap":[
        {
          "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths":[
            "/opt/cluster/infra",
            "/opt/cluster/htpc",
            "/opt/cluster/utils"
          ]
        }
      ]
    }
