---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - storageclass.yaml
  - deployment.yaml
  - configmap.yaml
