---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-infra
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: /opt/cluster/infra
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-htpc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: /opt/cluster/htpc
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-utils
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: /opt/cluster/utils
