---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-certificate
spec:
  secretName: placeholder-secret-name
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "htpc,infra,utils"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "htpc,infra,utils"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  commonName: "*.my-homelab.party"
  dnsNames:
    - "*.my-homelab.party"
