---
  name: Merge CI
  on:
    push:
      branches:
        - master
  jobs:
    update-manifests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Setup kustomize
          uses: fluxcd/pkg/actions/kustomize@main
        - name: Update manifests for arm
          run: ./update-manifests.sh arm
        - name: Update manifests for x86
          run: ./update-manifests.sh x86
        - name: Commit and push if manifest changed
          run: |-
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add install_armhf.yaml || exit 0
            git add install_x86.yaml || exit 0
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
