---
name: CI
on: [push]  # yamllint disable-line rule:truthy
jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
  validate:
    runs-on: ubuntu-latest
    needs: [yaml-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Validate manifests
        run: ./validate.sh
  update-manifests:
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Update manifests for arm
        run: ./update-manifests.sh arm
      - name: Update manifests for x86
        run: ./update-manifests.sh x86
