---
  name: Linting and validation
  on: [pull_request, push]  # yamllint disable-line rule:truthy
  jobs:
    yaml-lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.1
        - name: yaml-lint
          uses: ibiqlik/action-yamllint@v3.1.1
    validate:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Setup tools
          uses: ./.github/actions/tools
        - name: Validate manifests
          run: ./validate.sh
