---
name: Pull Request CI
on: [pull_request] # yamllint disable-line rule:truthy

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          fix: true
          globs: "**/*.md"
          config: .markdownlint.yaml

  validate:
    runs-on: ubuntu-latest
    needs: [markdownlint, yaml-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Setup ksops
        run: source <(curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh)
      - name: Setup AGE key
        run: |
          echo "${{ secrets.AGE_KEY }}" > /tmp/age-key.txt
          chmod 600 /tmp/age-key.txt
      - name: Validate manifests
        env:
          SOPS_AGE_KEY_FILE: /tmp/age-key.txt
        run: ./scripts/validate.sh

  detect-secrets:
    runs-on: ubuntu-latest
    needs: [yaml-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.90.2
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  test-build:
    needs: [validate, detect-secrets]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Setup ksops
        run: source <(curl -s https://raw.githubusercontent.com/viaduct-ai/kustomize-sops/master/scripts/install-ksops-archive.sh)
      - name: Setup AGE key
        run: |
          echo "${{ secrets.AGE_KEY }}" > /tmp/age-key.txt
          chmod 600 /tmp/age-key.txt
      - name: Test kustomize build
        env:
          SOPS_AGE_KEY_FILE: /tmp/age-key.txt
        run: ./scripts/update-manifests.sh
