---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: htpc
  namespace: htpc
spec:
  entryPoints:
    - websecure
    - websecure-local
  routes:
    - kind: Rule
      match: Host(`jellyfin.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: jellyfin
          port: 8096
    - kind: Rule
      match: Host(`jackett.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: jackett
          port: 9117
    - kind: Rule
      match: Host(`sonarr.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: sonarr
          port: 8989
    - kind: Rule
      match: Host(`radarr.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: radarr
          port: 7878
    - kind: Rule
      match: Host(`transmission.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: transmission
          port: 9091
