---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
  namespace: htpc
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jellyfin.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: jellyfin
          port: 8096
    - kind: Rule
      match: Host(`prowlarr.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: prowlarr
          port: 9696
    - kind: Rule
      match: Host(`sonarr.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: sonarr
          port: 8989
    - kind: Rule
      match: Host(`radarr.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: radarr
          port: 7878
    - kind: Rule
      match: Host(`transmission.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: transmission
          port: 9091
    - kind: Rule
      match: Host(`flaresolverr.my-homelab.party`)
      priority: 0
      services:
        - kind: Service
          name: flaresolverr
          namespace: htpc
          port: 8191
