---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

resources:
  - jackett
  - jellyfin
  - radarr
  - sonarr
  - transmission
  - ingress-route.yaml
  - namespace.yaml
  - persistent-volume-claim.yaml
