---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: htpc

resources:
  - flaresolverr
  - jellyfin
  - prowlarr
  - radarr
  - sonarr
  - transmission
  - ingress-route.yaml
  - persistent-volume-claim.yaml
