---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: htpc-pvc
spec:
  storageClassName: cluster-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      type: arr-stack
