apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/infra

components:
  - ../environment/production-infra # Change to staging-infra for staging
  - ../environment/production-ingress # Change to staging-ingress for staging
