apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/infra

components:
  - ../environment/staging-infra # Change to production-infra for production
  - ../environment/staging-ingress # Change to production-ingress for production
